import { expect, test } from '@playwright/test'
import { installSession, mockProfile } from './fixtures/auth'

test.beforeEach(async ({ page }) => {
  await mockProfile(page)
  await installSession(page)
})

test('顾客经营页签、顾客回访子页签和顾客跟进工作区', async ({ page }) => {
  await page.goto('/customers')
  await expect(page.getByRole('heading', { name: '顾客经营' })).toBeAttached()
  await expect(page.getByRole('tab')).toHaveText(['顾客列表', '高级查询', '顾客寄存', '顾客回访', '顾客跟进'])
  await expect(page.getByRole('columnheader')).toHaveText(['顾客信息', '顾客资产', '累计消费', '上次消费信息', '操作'])
  await expect(page.locator('.customer-card-filter').getByText('持卡', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '搜索会员卡' })).toBeVisible()
  await expect(page.locator('.customer-card-filter')).toHaveCount(1)
  const cardFilter = page.getByRole('combobox', { name: '会员卡筛选类型' })
  await cardFilter.click()
  await cardFilter.press('ArrowDown')
  await cardFilter.press('Enter')
  await expect(page.getByRole('textbox', { name: '搜索会员卡' })).toBeDisabled()
  await cardFilter.click()
  await cardFilter.press('ArrowUp')
  await cardFilter.press('Enter')
  await expect(page.getByRole('textbox', { name: '搜索会员卡' })).toBeEnabled()
  await page.getByRole('tab', { name: '顾客回访', exact: true }).click()
  await expect(page).toHaveURL(/\/customers\?tab=visit$/)
  await expect(page.getByRole('tab', { name: '回访明细', exact: true })).toHaveAttribute('aria-selected', 'true')
  const employeeSearchCombo = page.locator('.customer-search-combo')
  await expect(employeeSearchCombo.getByRole('combobox', { name: '回访员工类型' })).toBeVisible()
  await expect(employeeSearchCombo.locator('input[placeholder="输入员工姓名/工号"]')).toBeVisible()
  await expect(employeeSearchCombo.locator('.ant-input-search-btn')).toBeVisible()
  if ((await page.viewportSize())!.width > 767) expect((await employeeSearchCombo.boundingBox())!.width).toBeGreaterThan(450)
  const visitDateFilter = page.locator('.customer-date-filter')
  await expect(visitDateFilter.getByRole('combobox', { name: '回访时间类型' })).toBeVisible()
  await expect(visitDateFilter.getByPlaceholder('开始日期')).toBeVisible()
  await expect(page.getByRole('status', { name: '回访明细暂无相关数据' })).toBeVisible()
  await page.getByRole('tab', { name: '回访到店', exact: true }).click()
  await expect(page.getByRole('status', { name: '回访到店暂无相关数据' })).toBeVisible()
  await page.getByRole('tab', { name: '回访计划规则', exact: true }).click()
  await expect(page).toHaveURL(/visitTab=rules$/)
  await expect(page.getByRole('button', { name: '新增回访计划', exact: true })).toBeVisible()
  await expect(page.getByRole('status', { name: '回访计划规则暂无相关数据' })).toBeVisible()
  await page.getByRole('tab', { name: '顾客跟进', exact: true }).click()
  await expect(page.getByText('未分配跟踪员工', { exact: true })).toBeVisible()
  await expect(page.getByText('总顾客数', { exact: true })).toBeVisible()
  await expect(page.getByText('模拟顾客A', { exact: true })).toBeVisible()
  await expect(page.getByText('小杨', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: '跟踪员工', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '顾客寄存', exact: true }).click()
  await expect(page.getByText('产品寄存余量', { exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader')).toHaveText(['顾客信息', '门店信息', '操作信息', '品项信息', '备注', '操作'])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('高级查询条件分组有明确选中态并可应用', async ({ page }) => {
  await page.goto('/customers?tab=advanced')
  await expect(page.getByText('条件分类：', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '基本信息', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: '资产信息', exact: true }).click()
  await expect(page.getByRole('tab', { name: '资产信息', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('button', { name: '会员卡', exact: true }).click()
  await expect(page.getByRole('button', { name: '会员卡', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('columnheader', { name: '顾客信息', exact: true })).toBeVisible()
})

test('首页顾客回访提醒打开独立模块，库存预警打开抽屉', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '顾客回访提醒', exact: true }).click()
  await expect(page).toHaveURL(/\/customer-reminders$/)
  await expect(page.getByRole('heading', { name: '顾客回访提醒' })).toBeVisible()
  await expect(page.getByRole('status', { name: '顾客回访提醒暂无相关数据' })).toBeVisible()
  await expect(page.getByRole('columnheader')).toHaveText(['顾客信息', '回访场景', '计划回访时间', '回访员工', '状态', '操作'])
  await expect(page.getByRole('combobox', { name: '回访门店' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: '回访员工类型' })).toBeVisible()
  await expect(page.locator('.customer-search-combo .ant-input-search-btn')).toBeVisible()
  await expect(page.locator('.customer-date-filter').getByRole('combobox', { name: '回访时间类型' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/')
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('button', { name: '库存预警', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '库存预警' })).toBeVisible()
  await expect(page.getByRole('columnheader')).toHaveText(['#', '所属仓库', '产品类别', '产品信息', '单位', '库存数量', '库存下限', '预警值', '操作'])
  await expect(page.getByRole('status', { name: '库存预警列表暂无相关数据' })).toBeVisible()
  await page.getByRole('button', { name: '返回首页' }).click()
  await expect(page).toHaveURL(/\/$/)
})
