import { mkdir } from 'node:fs/promises'
import { test, expect } from '@playwright/test'
import type { Locator, Page } from '@playwright/test'
import dayjs from 'dayjs'
import { installOrders, sampleOrder } from './fixtures/orders'

async function fits(page: Page, dialog?: Locator) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  if (dialog) {
    await expect(dialog).not.toHaveClass(/ant-zoom-(appear|enter|leave)/)
    const bounds = (await dialog.boundingBox())!, viewport = page.viewportSize()!
    expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.y).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(viewport.width + 1); expect(bounds.y + bounds.height).toBeLessThanOrEqual(viewport.height + 1)
  }
}
async function choose(page: Page, label: string, option: string) {
  await page.getByLabel(label, { exact: true }).click()
  await page.locator('.ant-select-dropdown:visible').getByText(option, { exact: true }).click()
}
const currentList = (state: Awaited<ReturnType<typeof installOrders>>) => state.requests.filter(request => request.path === '/').at(-1)!

test('顾客经营分组与三个订单页签复刻，空状态和五种屏幕无横向溢出', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const state = await installOrders(page, { empty: true })
  await page.goto('/')
  if (page.viewportSize()!.width < 768) await page.getByRole('button', { name: '打开导航' }).click()
  await expect(page.locator('.ant-menu-item-group-title:visible').getByText('顾客经营', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '订单管理', exact: true }).first().click()
  await expect(page.getByRole('tab')).toHaveText(['订单列表', '未完成订单列表', '尾款单'])
  await expect(page.getByText('暂无相关数据', { exact: true })).toBeVisible()
  await expect(page.getByRole('group', { name: '消费类型', exact: true }).getByRole('button')).toHaveCount(16)
  await expect(page.getByRole('group', { name: '支付方式', exact: true }).getByRole('button')).toHaveCount(25)
  await expect(page.getByText('当前共搜索到0条记录', { exact: true })).toBeVisible()
  await fits(page)
  await mkdir('artifacts', { recursive: true })
  await page.screenshot({ path: `artifacts/orders-empty-${info.project.name}.png`, fullPage: true })
  await page.getByRole('tab', { name: '未完成订单列表', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: '挂单编号', exact: true })).toBeVisible()
  await expect.poll(() => currentList(state).params.tab).toBe('pending')
  expect(currentList(state).params.startDate).toBe(dayjs().format('YYYY-MM-DD'))
  await expect(page.getByRole('group', { name: '消费类型', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '订单核对设置', exact: true })).toHaveCount(0)
  await fits(page)
  await page.getByRole('tab', { name: '尾款单', exact: true }).click()
  await expect.poll(() => currentList(state).params.tab).toBe('balance')
  expect(currentList(state).params.startDate).toBeUndefined()
  await expect(page.getByRole('columnheader', { name: '订单编号', exact: true })).toBeVisible()
  await fits(page)
  expect(errors).toEqual([])
})

test('顾客订单员工搜索、组合筛选、排序分页和重置发送服务端参数', async ({ page }) => {
  const state = await installOrders(page)
  state.rows = Array.from({ length: 24 }, (_, i) => sampleOrder(i + 1))
  await page.goto('/orders')
  await expect(page.getByText('当前共搜索到24条记录', { exact: true })).toBeVisible()
  await page.getByRole('listitem', { name: '2', exact: true }).click()
  await expect.poll(() => currentList(state).params.page).toBe('2')
  await choose(page, '搜索类型', '订单')
  const search = page.getByRole('searchbox', { name: '搜索订单', exact: true })
  await expect(search).toHaveAttribute('placeholder', '输入订单编号')
  await search.fill('DD202609220001'); await search.press('Enter')
  await expect(page.getByText('当前共搜索到1条记录', { exact: true })).toBeVisible()
  expect(currentList(state).params).toMatchObject({ searchType: 'ORDER', keyword: 'DD202609220001', page: '1' })
  await choose(page, '搜索类型', '员工'); await search.fill('EMP001'); await search.press('Enter')
  await expect(page.getByText('当前共搜索到24条记录', { exact: true })).toBeVisible()
  await page.getByRole('group', { name: '消费类型', exact: true }).getByRole('button', { name: '项目', exact: true }).click()
  await page.getByRole('group', { name: '支付方式', exact: true }).getByRole('button', { name: '微信', exact: true }).click()
  await page.getByRole('group', { name: '核对状态', exact: true }).getByRole('button', { name: '未核对', exact: true }).click()
  await choose(page, '消费门店', '上海中心店')
  await expect.poll(() => currentList(state).params.storeId).toBe('11')
  expect(currentList(state).params).toMatchObject({ consumptionType: 'SERVICE', paymentMethod: 'WECHAT', verification: 'UNVERIFIED', searchType: 'STAFF' })
  await page.getByRole('columnheader', { name: /订单编号/ }).click()
  await expect.poll(() => currentList(state).params.sortBy).toBe('orderNo')
  expect(currentList(state).params.sortDirection).toBe('asc')
  await page.getByRole('button', { name: /^重\s*置$/ }).click()
  await expect(search).toHaveValue('')
  await expect.poll(() => currentList(state).params.searchType).toBe('CUSTOMER')
  expect(currentList(state).params.consumptionType).toBeUndefined()
  expect(currentList(state).params.storeId).toBeUndefined()
  await fits(page)
})

test('订单核对设置可取消重置、持久保存、禁用和处理版本冲突', async ({ page }, info) => {
  const state = await installOrders(page, { empty: true })
  await page.goto('/orders')
  const open = page.getByRole('button', { name: '订单核对设置', exact: true })
  await open.click()
  const dialog = page.getByRole('dialog', { name: '订单核对设置', exact: true }), checkbox = dialog.getByRole('checkbox')
  await expect(dialog.getByRole('radio', { name: '启用', exact: true })).toBeChecked()
  await expect(checkbox).toBeChecked()
  await fits(page, dialog)
  await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: `artifacts/orders-settings-${info.project.name}.png`, fullPage: true })
  await checkbox.uncheck(); await dialog.getByRole('button', { name: /^取\s*消$/ }).click(); await expect(dialog).toBeHidden()
  await open.click(); await expect(checkbox).toBeChecked()
  await checkbox.uncheck(); await dialog.getByRole('radio', { name: '禁用', exact: true }).check()
  await expect(checkbox).toBeDisabled()
  await dialog.getByRole('button', { name: /^保\s*存$/ }).click(); await expect(dialog).toBeHidden()
  expect(state.settings.get(1)).toEqual({ enabled: false, recheckAfterPerformanceChange: false, version: 1 })
  await page.reload(); await open.click()
  await expect(dialog.getByRole('radio', { name: '禁用', exact: true })).toBeChecked()
  await dialog.getByRole('radio', { name: '启用', exact: true }).check()
  state.conflict = true
  await dialog.getByRole('button', { name: /^保\s*存$/ }).click()
  await expect(dialog.getByText('设置已被其他人更新，请重新加载后保存')).toBeVisible()
  await expect(dialog).toBeVisible(); expect(state.settings.get(1)?.enabled).toBe(false)
  state.conflict = false
  await dialog.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(dialog.getByRole('radio', { name: '禁用', exact: true })).toBeChecked()
  await page.keyboard.press('Escape'); await expect(dialog).toBeHidden(); await expect(open).toBeFocused()
})

test('订单详情、金额精度、核对与取消核对，错误展示与重试', async ({ page }) => {
  const state = await installOrders(page)
  state.fail = '/'
  await page.goto('/orders')
  await expect(page.getByText('服务暂时不可用，请稍后重试')).toBeVisible()
  await expect(page.getByText('暂无相关数据', { exact: true })).toHaveCount(0)
  state.fail = ''; await page.getByRole('button', { name: '重试', exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: '测试顾客1' })
  await expect(row).toContainText('¥100.30')
  await row.getByRole('button', { name: '查看', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '订单详情', exact: true })
  await expect(dialog).toContainText('¥40.20'); await expect(dialog).toContainText('微信')
  await fits(page, dialog)
  await dialog.locator('.ant-modal-footer').getByRole('button', { name: /^关\s*闭$/ }).click()
  await row.getByRole('button', { name: '核对', exact: true }).click()
  await expect(row.getByText('已核对', { exact: true })).toBeVisible()
  expect(state.requests.filter(request => request.method === 'POST').at(-1)?.body).toEqual({ verified: true, version: 0 })
  await row.getByRole('button', { name: '取消核对', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '确认取消核对', exact: true }).click()
  await expect(row.getByText('未核对', { exact: true })).toBeVisible()
  expect(state.rows[0].version).toBe(2)
  await fits(page)
})

test('平台汇总全部企业，选定企业后设置与核对始终绑定目标租户', async ({ page }) => {
  const state = await installOrders(page, { platform: true })
  await page.goto('/orders')
  await expect(page.getByText('当前共搜索到2条记录', { exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: '所属企业', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '订单核对设置', exact: true })).toBeDisabled()
  await page.getByRole('row').filter({ hasText: '测试顾客3' }).getByRole('button', { name: '核对', exact: true }).click()
  await expect.poll(() => state.requests.filter(request => request.method === 'POST').at(-1)?.tenant).toBe('2')
  await choose(page, '选择企业范围', '北京美业企业（company-b）')
  await expect(page.getByText('当前共搜索到1条记录', { exact: true })).toBeVisible()
  await expect(page.getByText('测试顾客1', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '订单核对设置', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '订单核对设置', exact: true })
  await dialog.getByRole('radio', { name: '禁用', exact: true }).check()
  await dialog.getByRole('button', { name: /^保\s*存$/ }).click(); await expect(dialog).toBeHidden()
  expect(state.requests.filter(request => request.method === 'PUT').at(-1)?.tenant).toBe('2')
  expect(state.settings.get(2)?.enabled).toBe(false); expect(state.settings.get(1)?.enabled).toBe(true)
  await page.getByRole('tab', { name: '未完成订单列表', exact: true }).click()
  await expect.poll(() => currentList(state).params.tab).toBe('pending')
  expect(currentList(state).tenant).toBe('2')
  await choose(page, '选择企业范围', '上海美业企业（company-a）')
  await expect(page.getByText('测试顾客2', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '未完成订单列表', exact: true })).toHaveAttribute('aria-selected', 'true')
  await fits(page)
})

test('订单权限保护、只读设置，以及未授权地址不显示订单', async ({ page }) => {
  const state = await installOrders(page, { permissions: ['home:read', 'orders:read', 'order-settings:read'] })
  state.rows.forEach(row => { row.canVerify = false })
  await page.goto('/orders')
  await expect(page.getByText('测试顾客1', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '核对', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '订单核对设置', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '订单核对设置', exact: true })
  await expect(dialog.getByRole('radio', { name: '启用', exact: true })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: /^保\s*存$/ })).toHaveCount(0)
  await dialog.getByRole('button', { name: /^取\s*消$/ }).click(); await expect(dialog).toBeHidden()
  expect(state.requests.some(request => request.method !== 'GET')).toBe(false)
  await page.context().clearCookies()
  await installOrders(page, { permissions: ['home:read'] })
  await page.goto('/orders')
  await expect(page.getByText('暂无订单查看权限', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab')).toHaveCount(0)
})

test('PC与PAD切换保留筛选，手机及横屏日期弹层和设置完整可操作', async ({ page }) => {
  await installOrders(page, { empty: true })
  await page.goto('/orders')
  await page.getByRole('group', { name: '消费类型', exact: true }).getByRole('button', { name: '产品', exact: true }).click()
  const original = page.viewportSize()!
  await page.setViewportSize({ width: 1440, height: 1000 })
  const workspace = page.locator('.workspace'), toggle = page.locator('.device-mode')
  if ((await workspace.getAttribute('data-layout-mode')) === 'pad') await toggle.click()
  await toggle.click(); await expect(workspace).toHaveAttribute('data-layout-mode', 'pad')
  expect((await workspace.boundingBox())!.width).toBe(1024)
  await expect(page.getByRole('group', { name: '消费类型', exact: true }).getByRole('button', { name: '产品', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await fits(page)
  await toggle.click(); await expect(workspace).toHaveAttribute('data-layout-mode', 'pc')
  expect((await workspace.boundingBox())!.width).toBe(1440)
  for (const viewport of [original, { width: 320, height: 740 }, { width: 844, height: 390 }]) {
    await page.setViewportSize(viewport)
    await page.getByPlaceholder('开始日期', { exact: true }).click()
    await expect(page.locator('.responsive-range-popup:visible')).toBeVisible()
    const date = dayjs().format('YYYY-MM-DD')
    await page.locator(`.responsive-range-popup:visible td[title="${date}"]`).first().click()
    await page.locator(`.responsive-range-popup:visible td[title="${date}"]`).first().click()
    await expect(page.locator('.responsive-range-popup:visible')).toHaveCount(0)
    await fits(page)
    await page.getByRole('button', { name: '订单核对设置', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '订单核对设置', exact: true })
    await expect(dialog.getByRole('radio', { name: '启用', exact: true })).toBeVisible()
    await fits(page, dialog)
    await dialog.getByRole('button', { name: /^取\s*消$/ }).click()
    await expect(dialog).toBeHidden()
  }
})
