import { mkdir, readFile } from 'node:fs/promises'
import { test, expect as baseExpect } from '@playwright/test'
import type { Page, Locator } from '@playwright/test'
import dayjs from 'dayjs'
import { installSms, smsRecord } from './fixtures/sms'

// Intercepted Vite reloads bypass HTTP caching; allow the page to finish loading on the local Windows runner.
const expect = baseExpect.configure({ timeout: 10_000 })

async function fits(page: Page, dialog?: Locator) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  if (dialog) {
    await expect(dialog).not.toHaveClass(/ant-zoom-(appear|enter|leave)/)
    const bounds = (await dialog.boundingBox())!, view = page.viewportSize()!
    expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.y).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(view.width + 1); expect(bounds.y + bounds.height).toBeLessThanOrEqual(view.height + 1)
  }
}
test('拓客工具短信入口与四组十三个设置，三个页签复刻及响应式', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await installSms(page); await page.goto('/')
  if (page.viewportSize()!.width < 768) await page.getByRole('button', { name: '打开导航' }).click()
  if (page.viewportSize()!.width >= 768 && page.viewportSize()!.width < 1024) await page.getByRole('button', { name: 'PAD模式', exact: true }).click()
  await expect(page.locator('.ant-menu-item-group-title:visible').getByText('拓客工具', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '短信', exact: true }).first().click()
  await expect(page.getByRole('tab')).toHaveText(['短信设置', '短信发送记录', '短信余额充值'])
  await expect(page.getByRole('switch')).toHaveCount(13)
  await expect(page.locator('.sms-settings-card h2')).toHaveText(['交易提醒', '预约提醒', '特殊日期提醒', '合伙人相关'])
  await expect(page.getByRole('switch', { name: '开卡成功', exact: true })).not.toBeChecked()
  await expect(page.getByText(/短信发送与充值收款通道尚未接入/)).toBeVisible()
  await fits(page); await mkdir('artifacts', { recursive: true })
  await page.screenshot({ path: `artifacts/sms-settings-${info.project.name}.png`, fullPage: true })
  await page.getByRole('tab', { name: '短信发送记录', exact: true }).click()
  await expect(page.getByText('暂无数据', { exact: true })).toBeVisible(); await fits(page)
  await page.getByRole('tab', { name: '短信余额充值', exact: true }).click()
  await expect(page.locator('.sms-package')).toHaveCount(5)
  await expect(page.getByLabel('剩余短信条数')).toHaveText('0'); await fits(page)
  await page.screenshot({ path: `artifacts/sms-billing-${info.project.name}.png`, fullPage: true })
  expect(errors).toEqual([])
})

test('通知开关持久保存，失败保持原值，版本冲突重新加载', async ({ page }) => {
  const state = await installSms(page); await page.goto('/sms')
  const toggle = page.getByRole('switch', { name: '储值卡-充值', exact: true })
  await toggle.click(); await expect(toggle).toBeChecked()
  await page.reload(); await expect(toggle).toBeChecked()
  state.conflict = true; await toggle.click()
  await expect(page.getByText('短信设置已被其他人更新，请重新加载后保存', { exact: true })).toBeVisible()
  await expect(toggle).toBeChecked()
  state.conflict = false; await page.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(toggle).toBeChecked(); await toggle.click(); await expect(toggle).not.toBeChecked()
  expect(state.requests.filter(req => req.method === 'PUT').at(-1)?.body).toEqual({ enabled: false, version: 1 })
})

test('预约提醒按截图提前一分钟，取消不写入，保存后可回显', async ({ page }, info) => {
  test.slow() // Includes validation, close/reopen, screenshots and a complete Vite page reload.
  const state = await installSms(page); await page.goto('/sms')
  const toggle = page.getByRole('switch', { name: '预约提醒', exact: true })
  await toggle.click()
  const dialog = page.getByRole('dialog', { name: '预约提醒设置', exact: true })
  await fits(page, dialog)
  await expect(dialog.getByRole('spinbutton')).toHaveValue('1')
  await page.screenshot({ path: `artifacts/sms-appointment-rule-${info.project.name}.png`, fullPage: true })
  await dialog.getByRole('button', { name: /^取\s*消$/ }).click(); await expect(dialog).toBeHidden()
  await expect(toggle).not.toBeChecked(); expect(state.requests.filter(req => req.method === 'PUT')).toHaveLength(0)
  await toggle.click(); await dialog.getByRole('spinbutton').fill('')
  await dialog.getByRole('button', { name: /^确\s*定$/ }).click()
  await expect(dialog.getByText('请输入分钟数', { exact: true })).toBeVisible()
  await dialog.getByRole('spinbutton').fill('1')
  await dialog.getByRole('button', { name: /^确\s*定$/ }).click(); await expect(dialog).toBeHidden(); await expect(toggle).toBeChecked()
  await page.reload(); await expect(page.getByText('提前 1 分钟提醒', { exact: true })).toBeVisible()
  expect(state.requests.filter(req => req.method === 'PUT').at(-1)?.body).toEqual({ enabled: true, version: 0, config: { leadMinutes: 1 } })
})

test('生日默认福利直接保存，开启自定义才校验，关闭后保留内容且取消不落库', async ({ page }, info) => {
  test.slow() // Multiple saves, reloads and cancel/reopen cycles verify persisted versus draft state.
  const state = await installSms(page); await page.goto('/sms')
  await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  const birthday = page.getByRole('dialog', { name: '生日短信提醒设置', exact: true })
  const custom = birthday.getByRole('switch', { name: '自定义到店福利', exact: true })
  const confirm = birthday.getByRole('button', { name: /^确\s*定$/ })
  await expect(custom).not.toBeChecked()
  await expect(birthday.getByText('设置为0表示当天发送', { exact: true })).toBeVisible()
  await expect(birthday.getByText('默认为：到店可享受生日权益', { exact: true })).toBeVisible()
  await expect(birthday.getByLabel('生日权益', { exact: true })).toHaveCount(0)
  await fits(page, birthday)
  await page.screenshot({ path: `artifacts/sms-birthday-default-${info.project.name}.png`, fullPage: true })
  await birthday.getByRole('spinbutton').fill('0'); await confirm.click(); await expect(birthday).toBeHidden()
  await page.reload(); await expect(page.getByText('生日当天发送', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  await expect(custom).not.toBeChecked(); await custom.click()
  await birthday.getByLabel('生日权益', { exact: true }).fill(''); await confirm.click()
  await expect(birthday.getByText('请输入生日权益', { exact: true })).toBeVisible()
  await birthday.getByLabel('到店时间说明', { exact: true }).fill('生日当月')
  await birthday.getByLabel('生日权益', { exact: true }).fill('专属护理体验')
  await fits(page, birthday)
  await page.screenshot({ path: `artifacts/sms-birthday-custom-${info.project.name}.png`, fullPage: true })
  await custom.click(); await expect(birthday.getByLabel('生日权益', { exact: true })).toHaveCount(0)
  await confirm.click(); await expect(birthday).toBeHidden()
  await page.reload(); await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  await expect(custom).not.toBeChecked(); await custom.click()
  await expect(birthday.getByLabel('生日权益', { exact: true })).toHaveValue('专属护理体验')
  await expect(birthday.getByLabel('到店时间说明', { exact: true })).toHaveValue('生日当月')
  await confirm.click(); await expect(birthday).toBeHidden()
  await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  await expect(custom).toBeChecked(); await custom.click()
  await birthday.getByRole('button', { name: /^取\s*消$/ }).click(); await expect(birthday).toBeHidden()
  await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  await expect(custom).toBeChecked()
  await birthday.getByRole('button', { name: /^取\s*消$/ }).click()
  await expect(page.getByRole('switch', { name: '生日祝福', exact: true })).not.toBeChecked()
  expect(state.requests.some(req => /send|pay/.test(req.path))).toBe(false)
})

test('已有生日自定义配置正确回显，窄屏与横屏弹窗可关闭', async ({ page }) => {
  const state = await installSms(page)
  const item = state.settings.get(1)!.groups.flatMap(group => group.templates).find(row => row.code === 'BIRTHDAY_GREETING')!
  item.config = { advanceDays: 2, sendTime: '10:30', visitNote: '生日当周', benefitNote: '原有生日权益' }; item.version = 2; item.enabled = true
  await page.goto('/sms'); await page.getByRole('button', { name: '设置生日祝福', exact: true }).click()
  const birthday = page.getByRole('dialog', { name: '生日短信提醒设置', exact: true })
  await expect(birthday.getByRole('switch', { name: '自定义到店福利', exact: true })).toBeChecked()
  await expect(birthday.getByLabel('生日权益', { exact: true })).toHaveValue('原有生日权益')
  if (page.viewportSize()!.width < 768) {
    await page.setViewportSize({ width: 320, height: 568 }); await fits(page, birthday)
    await page.setViewportSize({ width: 844, height: 390 }); await fits(page, birthday)
  }
  await birthday.getByRole('button', { name: /^确\s*定$/ }).click(); await expect(birthday).toBeHidden()
  expect((state.requests.filter(req => req.method === 'PUT').at(-1)?.body?.config as { sendTime: string }).sendTime).toBe('10:30')
})

test('发送记录服务器筛选分页、下载全部筛选结果，加载失败可重试', async ({ page }) => {
  const state = await installSms(page); state.rows = Array.from({ length: 22 }, (_, i) => smsRecord(i + 1)); state.fail = '/records'
  await page.goto('/sms?tab=records')
  await expect(page.getByText('服务暂时不可用，请稍后重试', { exact: true })).toBeVisible()
  await expect(page.getByText('暂无数据', { exact: true })).toHaveCount(0)
  state.fail = ''; await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.getByText('共 22 条记录', { exact: true })).toBeVisible()
  const last = () => state.requests.filter(req => req.path === '/records').at(-1)!
  expect(last().params.startDate).toBe(dayjs().startOf('month').format('YYYY-MM-DD'))
  await page.getByRole('listitem', { name: '2', exact: true }).click(); await expect.poll(() => last().params.page).toBe('2')
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '下载报表', exact: true }).click()
  const file = await download; expect(file.suggestedFilename()).toContain('短信发送记录')
  const csv = await readFile((await file.path())!, 'utf8'); expect(csv).toContain('已成功办理会员卡22')
  const exported = state.requests.find(req => req.path === '/records/export')!; expect(exported.params.page).toBeUndefined()
  const search = page.getByRole('searchbox', { name: '搜索手机号', exact: true }); await search.fill('13800000001'); await search.press('Enter')
  await expect(page.getByText('共 1 条记录', { exact: true })).toBeVisible(); expect(last().params.page).toBe('1'); expect(last().params.phone).toBe('13800000001')
  await fits(page)
})

test('套餐先选中再支付，金额联动且重复选择不创建单，确认可取消', async ({ page }, info) => {
  test.slow() // Exercises selection, checkout, cancellation, history and a full page reload.
  const state = await installSms(page); await page.goto('/sms?tab=billing')
  const open = page.getByRole('button', { name: /1000条短信包.*68/ })
  const other = page.getByRole('button', { name: /3000条短信包.*180/ })
  const pay = page.getByRole('button', { name: '立即支付', exact: true })
  await expect(pay).toHaveCount(0)
  await open.click()
  await expect(open).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('应付金额', { exact: true })).toHaveText('¥68')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await other.focus(); await other.press('Enter')
  await expect(other).toHaveAttribute('aria-pressed', 'true'); await expect(open).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByLabel('应付金额', { exact: true })).toHaveText('¥180')
  await other.click(); expect(state.requests.some(req => req.method === 'POST')).toBe(false)
  await expect(other).toHaveCSS('background-color', 'rgb(230, 244, 255)')
  await fits(page)
  await page.screenshot({ path: `artifacts/sms-package-selected-${info.project.name}.png`, fullPage: true })
  await pay.click()
  const dialog = page.getByRole('dialog', { name: '确认短信充值套餐', exact: true })
  await expect(dialog).toContainText('不会扣款、发送短信或增加余额'); await fits(page, dialog)
  await dialog.getByRole('button', { name: /^取\s*消$/ }).click(); await expect(dialog).toBeHidden(); expect(state.recharges).toHaveLength(0)
  await expect(other).toHaveAttribute('aria-pressed', 'true'); await expect(pay).toBeFocused()
  await open.click(); await pay.click(); await dialog.getByRole('button', { name: '创建待支付订单', exact: true }).click()
  const created = page.getByRole('dialog', { name: '充值订单已记录', exact: true })
  await expect(created.getByText('待支付', { exact: true })).toBeVisible()
  expect(state.recharges).toHaveLength(1); expect(state.requests.filter(req => req.method === 'POST')[0].body?.idempotencyKey).toMatch(/^[\da-f-]{36}$/)
  await expect(page.getByLabel('剩余短信条数')).toHaveText('0')
  await created.getByRole('button', { name: '查看充值记录', exact: true }).click()
  const history = page.getByRole('dialog', { name: '短信充值记录', exact: true })
  await expect(history.getByText('待支付', { exact: true })).toBeVisible(); await fits(page, history)
  await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: `artifacts/sms-recharges-${info.project.name}.png`, fullPage: true })
  await history.getByRole('button', { name: '取消订单', exact: true }).click()
  await page.getByRole('button', { name: '确认取消', exact: true }).click()
  await expect(history.getByText('已取消', { exact: true })).toBeVisible()
  await history.locator('.ant-modal-footer').getByRole('button').click()
  await expect(page.getByLabel('剩余短信条数')).toHaveText('0')
  await page.reload(); await page.getByRole('button', { name: '短信充值记录', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('已取消', { exact: true })).toBeVisible()
  await expect(pay).toHaveCount(0)
})

test('平台需选择企业才能写入，汇总记录和切换企业不串数据', async ({ page }) => {
  const state = await installSms(page, { platform: true }); state.rows = [smsRecord(1, 1), smsRecord(2, 2)]
  await page.goto('/sms')
  await expect(page.getByText('请选择要管理短信设置的企业', { exact: true })).toBeVisible()
  expect(state.requests.some(req => req.path === '/settings')).toBe(false)
  await page.getByRole('tab', { name: '短信余额充值', exact: true }).click()
  await expect(page.locator('.sms-package').first()).toBeDisabled()
  await page.getByRole('tab', { name: '短信发送记录', exact: true }).click()
  await expect(page.getByText('共 2 条记录', { exact: true })).toBeVisible()
  await page.getByLabel('选择企业范围', { exact: true }).click()
  await page.locator('.ant-select-dropdown:visible').getByText('上海美业企业（company-a）', { exact: true }).click()
  await expect(page.getByText('共 1 条记录', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '短信设置', exact: true }).click()
  await page.getByRole('switch', { name: '储值卡-充值', exact: true }).click()
  await expect(page.getByRole('switch', { name: '储值卡-充值', exact: true })).toBeChecked()
  expect(state.requests.filter(req => req.method === 'PUT').at(-1)?.tenant).toBe('1')
  await page.getByLabel('选择企业范围', { exact: true }).click()
  await page.locator('.ant-select-dropdown:visible').getByText('北京美业企业（company-b）', { exact: true }).click()
  await expect(page.getByRole('switch', { name: '储值卡-充值', exact: true })).not.toBeChecked()
  await expect.poll(() => state.requests.filter(req => req.path === '/settings').at(-1)?.tenant).toBe('2')
  await fits(page)
})

test('只读账号无发送导出充值权限，权限不足不请求接口', async ({ page }) => {
  const state = await installSms(page, { permissions: ['sms-settings:read', 'sms-records:read', 'sms-billing:read'] })
  await page.goto('/sms'); await expect(page.getByRole('switch', { name: '储值卡-充值', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: '短信发送记录', exact: true }).click()
  await expect(page.getByRole('button', { name: '下载报表', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: '短信余额充值', exact: true }).click()
  await expect(page.locator('.sms-package').first()).toBeDisabled(); expect(state.requests.every(req => req.method === 'GET')).toBe(true)
})
