import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import dayjs, { type Dayjs } from 'dayjs'
import { App, Button, Checkbox, DatePicker, Drawer, Empty, Form, Input, InputNumber, Modal, Popover, Radio, Result, Select, Slider, Space, Spin, Switch, Table, Tabs, Tag, TimePicker, Tooltip, Upload } from 'antd'
import { AppstoreOutlined, CalendarOutlined, CheckCircleOutlined, ClockCircleOutlined, DeleteOutlined, ExpandOutlined, LeftOutlined, PlusOutlined, RightOutlined, SettingOutlined, UnorderedListOutlined, UploadOutlined, UserOutlined } from '@ant-design/icons'
import { useSearchParams } from 'react-router-dom'
import { EnterpriseSelector } from '@/components/iam/PlatformDataPanel'
import { QueryError } from '@/components/iam/shared'
import { useAuth } from '@/context/AuthContext'
import { catalogRequest, useCatalogQuery } from '@/api/catalog'
import type { Department, PageResult } from '@/types/iam'
import '@/styles/appointment.css'

type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'ARRIVED' | 'DONE' | 'CANCELLED' | 'TEMP_BLOCK'
type ViewMode = 'staff' | 'room'
type DisplayMode = 'calendar' | 'list'
type OperationType = 'NORMAL' | 'TEMP_BLOCK' | 'RECURRING'

interface ResourceOption { id: number; name: string; code?: string }
interface CustomerPrefillRecord { name?: string; phone?: string; storeId?: number }
interface Appointment {
  id: number; departmentId: number; departmentName?: string; date: string; start: string; duration: number; customer: string; phone?: string
  service: string; staff: string; room: string; status: AppointmentStatus; color: string; note?: string; partySize: number
  needsTea: boolean; needsAirConditioner: boolean; bringsPet: boolean; bringsChild: boolean; needsBath: boolean; bookingType: OperationType
  createdAt?: string; updatedAt?: string
}
interface AppointmentFormValues {
  customer: string; phone?: string; partySize: number; service: string; date: Dayjs; start: Dayjs; duration: number; staff?: string; room?: string
  status: AppointmentStatus; confirmed?: boolean; color: string; needsTea: boolean; needsAirConditioner: boolean; bringsPet: boolean; bringsChild: boolean; needsBath: boolean
  note?: string; occurrences?: number
}
interface AppointmentSettings {
  departmentId: number; businessStart: string; businessEnd: string; bookableStaffIds: number[]; publicBookingEnabled: boolean; publicImageData?: string | null
  publicSlots: Array<{ start: string; end: string }>; publicWeekdays: number[]; closedDates: string[]; advanceMinutes: number; intervalMinutes: number; maxAdvanceDays: number; preventConflicts: boolean
}

const defaultStaffColumns = ['小杨', '李老师', '王店长', '前台']
const defaultRoomColumns = ['护理间 A', '护理间 B', 'VIP 房', '公共区']
const defaultServices = ['基础清洁护理', '补水修护护理', '肩颈舒缓', '产品试用咨询']
const statuses: Array<{ value: AppointmentStatus; label: string; color: string }> = [
  { value: 'PENDING', label: '待确认', color: '#faad14' }, { value: 'CONFIRMED', label: '待服务', color: '#1677ff' }, { value: 'ARRIVED', label: '已到店', color: '#13c2c2' },
  { value: 'DONE', label: '已完成', color: '#52c41a' }, { value: 'CANCELLED', label: '已取消', color: '#bfbfbf' }, { value: 'TEMP_BLOCK', label: '临时占用', color: '#722ed1' },
]
const colors = ['#1677ff', '#722ed1', '#13c2c2', '#fa8c16', '#eb2f96', '#52c41a']
const slots = Array.from({ length: 10 }, (_, index) => `${String(index + 10).padStart(2, '0')}:00`)
const defaultSettings = (departmentId: number): AppointmentSettings => ({ departmentId, businessStart: '09:00', businessEnd: '19:30', bookableStaffIds: [], publicBookingEnabled: true, publicImageData: null, publicSlots: [{ start: '09:00', end: '19:30' }], publicWeekdays: [1, 2, 3, 4, 5, 6, 7], closedDates: [], advanceMinutes: 120, intervalMinutes: 20, maxAdvanceDays: 30, preventConflicts: true })

function statusMeta(status: AppointmentStatus) { return statuses.find(item => item.value === status) ?? statuses[0] }
function minutesOf(value: string) { const [hour, minute] = value.slice(0, 5).split(':').map(Number); return (hour - 10) * 60 + minute }
function timeValue(value: string | undefined, fallback: string) { return dayjs(`2000-01-01 ${value || fallback}`) }
function formatDateTime(value: unknown) { if (!value) return '-'; const text = String(value).replace('T', ' '); return text.length > 16 ? text.slice(0, 16) : text }
function maskCustomerPhone(phone: string) { return phone.length >= 7 ? `${phone.slice(0, 3)}****${phone.slice(-4)}` : phone }
function resourceOptions(rows: Array<Record<string, unknown>> | undefined, fallback: string[], kind: 'staff' | 'room'): ResourceOption[] {
  const values = (rows ?? []).map((row, index) => ({ id: Number(row.id ?? index + 1), name: String(kind === 'staff' ? (row.nickname ?? row.username ?? '') : (row.name ?? '')), code: row.code ? String(row.code) : undefined })).filter(item => item.name)
  return values.length ? values : fallback.map((name, index) => ({ id: index + 1, name }))
}
function isUnassignedResource(value: string | undefined, viewMode: ViewMode) { return !value || value === '未选择' || (viewMode === 'room' && value === '未选择房间') }
function toAppointment(row: Record<string, unknown>): Appointment {
  const status = String(row.status ?? 'PENDING') as AppointmentStatus
  const bookingType = String(row.bookingType ?? (status === 'TEMP_BLOCK' ? 'TEMP_BLOCK' : 'NORMAL')) as OperationType
  return { id: Number(row.id), departmentId: Number(row.departmentId), departmentName: String(row.departmentName ?? ''), date: String(row.appointmentDate ?? ''), start: String(row.startTime ?? '').slice(0, 5), duration: Number(row.durationMinutes ?? 60), customer: String(row.customerName ?? ''), phone: row.phone ? String(row.phone) : undefined, service: String(row.serviceName ?? ''), staff: String(row.staffName ?? ''), room: String(row.roomName ?? ''), status, color: String(row.color ?? statusMeta(status).color), note: row.note ? String(row.note) : undefined, partySize: Number(row.partySize ?? 1), needsTea: Boolean(row.needsTea), needsAirConditioner: Boolean(row.needsAirConditioner), bringsPet: Boolean(row.bringsPet), bringsChild: Boolean(row.bringsChild), needsBath: Boolean(row.needsBath), bookingType, createdAt: row.createTime ? String(row.createTime) : undefined, updatedAt: row.updateTime ? String(row.updateTime) : undefined }
}

function eventDetail(appointment: Appointment, viewMode: ViewMode) {
  return <div className="appointment-event-popover"><strong>{appointment.customer || '临时占用'}</strong>{appointment.phone && <span>{appointment.phone}</span>}<div className="appointment-popover-divider" /><span>技师：{appointment.staff || '-'}</span><span>时间：{appointment.start} - {timeValue(appointment.start, '10:00').add(appointment.duration, 'minute').format('HH:mm')}</span><span>人数：{appointment.partySize} 人</span><span>房间：{appointment.room || '-'}</span><span>项目：{appointment.service || '-'}</span><span>备注：{appointment.note || '-'}</span><span>{viewMode === 'staff' ? '当前按技师维度展示' : '当前按房间维度展示'}</span></div>
}

function AppointmentEditor({ open, appointment, customerPrefill, defaultStart, defaultDate, viewMode, operationType, staffOptions, roomOptions, serviceOptions, onClose, onSave }: { open: boolean; appointment?: Appointment; customerPrefill?: { customer: string; phone?: string }; defaultStart: string; defaultDate: Dayjs; viewMode: ViewMode; operationType: OperationType; staffOptions: ResourceOption[]; roomOptions: ResourceOption[]; serviceOptions: string[]; onClose: () => void; onSave: (value: AppointmentFormValues) => Promise<void> }) {
  const [form] = Form.useForm<AppointmentFormValues>()
  const isTemp = operationType === 'TEMP_BLOCK'
  const isRecurring = operationType === 'RECURRING'
  useEffect(() => {
    if (!open) return
    form.setFieldsValue({ customer: appointment?.customer ?? customerPrefill?.customer ?? (isTemp ? '临时占用' : ''), phone: appointment?.phone ?? customerPrefill?.phone, partySize: appointment?.partySize ?? 1, service: appointment?.service ?? (isTemp ? '时间占用' : serviceOptions[0] ?? defaultServices[0]), date: dayjs(appointment?.date ?? defaultDate.format('YYYY-MM-DD')), start: timeValue(appointment?.start, defaultStart), duration: appointment?.duration ?? 60, staff: appointment?.staff || undefined, room: appointment?.room || undefined, status: appointment?.status ?? (isTemp ? 'TEMP_BLOCK' : 'PENDING'), confirmed: customerPrefill ? true : appointment?.status === 'CONFIRMED', color: appointment?.color ?? (isTemp ? colors[1] : colors[0]), needsTea: appointment?.needsTea ?? false, needsAirConditioner: appointment?.needsAirConditioner ?? false, bringsPet: appointment?.bringsPet ?? false, bringsChild: appointment?.bringsChild ?? false, needsBath: appointment?.needsBath ?? false, note: appointment?.note, occurrences: 4 })
  }, [appointment, customerPrefill, defaultDate, defaultStart, form, isTemp, open, roomOptions, serviceOptions, staffOptions, viewMode])
  const operationLabel = isTemp ? '临时占用' : isRecurring ? '长期固定时间预约' : customerPrefill ? '预约' : appointment ? '编辑预约' : '新增预约'
  return <Modal className="appointment-editor-modal" title={<span className="appointment-editor-title"><CalendarOutlined /> {operationLabel}</span>} open={open} width={620} centered destroyOnHidden onCancel={onClose} footer={<div className="appointment-dialog-actions"><Button onClick={onClose}>取消</Button><Button type="primary" onClick={() => form.submit()}>确认</Button></div>}><Form form={form} layout="vertical" onFinish={onSave} className="appointment-editor-form">
    <div className="appointment-form-section-title">顾客预约信息</div><div className="appointment-form-grid"><Form.Item name="customer" label="顾客姓名" rules={isTemp ? [] : [{ required: true, whitespace: true, message: '请输入顾客姓名' }]}><Input placeholder={isTemp ? '临时占用可不填写' : '例如：林女士'} maxLength={80} /></Form.Item><Form.Item name="phone" label="联系电话" rules={isTemp ? [] : [{ required: true, message: '请输入手机号' }]}><Input placeholder="请输入手机号" maxLength={30} /></Form.Item></div>
    <div className="appointment-form-grid appointment-form-grid--three"><Form.Item name="partySize" label="人数"><InputNumber min={1} max={30} style={{ width: '100%' }} /></Form.Item><Form.Item name="date" label="预约日期" rules={[{ required: true, message: '请选择日期' }]}><DatePicker format="YYYY-MM-DD" style={{ width: '100%' }} /></Form.Item>{!customerPrefill && <Form.Item name="status" label="状态"><Select options={statuses.map(item => ({ value: item.value, label: item.label }))} /></Form.Item>}</div>
    <div className="appointment-form-section-title">服务内容</div><div className="appointment-form-grid"><Form.Item name="service" label="预约项目" rules={isTemp ? [] : [{ required: true, message: '请选择预约项目' }]}><Select showSearch options={serviceOptions.map(value => ({ value, label: value }))} /></Form.Item><Form.Item name="staff" label="服务技师"><Select allowClear options={staffOptions.map(value => ({ value: value.name, label: value.name }))} placeholder="请选择技师" /></Form.Item></div>
    <div className="appointment-form-grid appointment-form-grid--three"><Form.Item name="start" label="开始时间" rules={[{ required: true, message: '请选择开始时间' }]}><TimePicker format="HH:mm" minuteStep={15} style={{ width: '100%' }} /></Form.Item><Form.Item name="duration" label="时长（分钟）" rules={[{ required: true, message: '请输入时长' }]}><InputNumber min={15} max={480} step={15} style={{ width: '100%' }} /></Form.Item><Form.Item name="room" label="房间"><Select allowClear options={roomOptions.map(value => ({ value: value.name, label: value.name }))} placeholder="请选择房间" /></Form.Item></div>
    {isRecurring && <Form.Item name="occurrences" label="重复次数" rules={[{ required: true, message: '请输入重复次数' }]}><InputNumber min={2} max={52} style={{ width: '100%' }} addonAfter="次，每周重复" /></Form.Item>}<Form.Item name="color" label="预约颜色" rules={[{ required: true, message: '请选择颜色' }]}><Radio.Group className="appointment-color-picker">{colors.map(color => <Radio.Button value={color} key={color}><span className="appointment-color-dot" style={{ background: color }} aria-label={color} /></Radio.Button>)}</Radio.Group></Form.Item>
    <div className="appointment-form-section-title">其他信息</div><div className="appointment-switch-grid">{customerPrefill && <Form.Item name="confirmed" valuePropName="checked" label="已确认"><Switch /></Form.Item>}<Form.Item name="needsTea" valuePropName="checked" label="预备茶点"><Switch /></Form.Item><Form.Item name="needsAirConditioner" valuePropName="checked" label="预备空调温度"><Switch /></Form.Item><Form.Item name="bringsPet" valuePropName="checked" label="携带宠物"><Switch /></Form.Item><Form.Item name="bringsChild" valuePropName="checked" label="携带儿童"><Switch /></Form.Item><Form.Item name="needsBath" valuePropName="checked" label="需要沐浴"><Switch /></Form.Item></div><Form.Item name="note" label="备注"><Input.TextArea rows={3} maxLength={500} placeholder="如有预约备注信息，可填写" showCount /></Form.Item>
  </Form></Modal>
}

function OperationChooser({ open, value, onChange, onCancel, onConfirm }: { open: boolean; value: OperationType; onChange: (value: OperationType) => void; onCancel: () => void; onConfirm: () => void }) {
  return <Modal className="appointment-operation-modal" title="选择操作类型" width={500} centered open={open} onCancel={onCancel} footer={<div className="appointment-dialog-actions"><Button onClick={onCancel}>取消</Button><Button type="primary" onClick={onConfirm}>确认</Button></div>}><Radio.Group value={value} onChange={event => onChange(event.target.value)} className="appointment-operation-options"><Radio value="NORMAL">新增预约</Radio><Radio value="TEMP_BLOCK">新增临时占用</Radio><Radio value="RECURRING">新增长期固定时间预约</Radio></Radio.Group></Modal>
}

function AppointmentSettingsDrawer({ open, tenantId, departmentId, staffOptions, onClose, onSaved }: { open: boolean; tenantId?: number; departmentId?: number; staffOptions: ResourceOption[]; onClose: () => void; onSaved: () => void }) {
  const { message } = App.useApp(); const [activeTab, setActiveTab] = useState('basic'); const [settings, setSettings] = useState<AppointmentSettings>(() => defaultSettings(departmentId ?? 0)); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [closedDate, setClosedDate] = useState<Dayjs>()
  useEffect(() => {
    if (!open || !departmentId) return
    setLoading(true)
    void catalogRequest<AppointmentSettings>(`/appointments/settings?departmentId=${departmentId}`, tenantId)
      .then(value => setSettings({
        ...defaultSettings(departmentId),
        ...value,
        bookableStaffIds: value.bookableStaffIds?.length ? value.bookableStaffIds : staffOptions.filter(item => item.id > 0).map(item => item.id),
      }))
      .catch(cause => void message.error(cause instanceof Error ? cause.message : '预约设置加载失败'))
      .finally(() => setLoading(false))
  }, [departmentId, message, open, staffOptions, tenantId])
  function patch<K extends keyof AppointmentSettings>(key: K, value: AppointmentSettings[K]) { setSettings(current => ({ ...current, [key]: value })) }
  function addClosedDate() { if (closedDate) { const value = closedDate.format('YYYY-MM-DD'); if (!settings.closedDates.includes(value)) patch('closedDates', [...settings.closedDates, value].sort()); setClosedDate(undefined) } }
  function readImage(file: File) { const reader = new FileReader(); reader.onload = () => patch('publicImageData', String(reader.result)); reader.readAsDataURL(file); return false }
  async function save() { if (!departmentId) return; setSaving(true); try { await catalogRequest('/appointments/settings', tenantId, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...settings, departmentId }) }); void message.success('预约设置已保存'); onSaved(); onClose() } catch (cause) { void message.error(cause instanceof Error ? cause.message : '预约设置保存失败') } finally { setSaving(false) } }
  return <Drawer className="appointment-settings-drawer" placement="right" size="min(1600px, calc(100vw - 70px))" title={<span className="appointment-drawer-title"><LeftOutlined onClick={onClose} />预约设置</span>} open={open} onClose={onClose} destroyOnHidden footer={<div className="drawer-actions"><Button onClick={onClose}>取消</Button><Button type="primary" loading={saving} onClick={() => void save()}>保存设置</Button></div>}>
    {loading ? <div className="appointment-settings-loading"><Spin /></div> : <div className="appointment-settings-content"><Tabs activeKey={activeTab} onChange={setActiveTab} items={[{ key: 'basic', label: '预约设置' }, { key: 'advanced', label: '高级设置' }]} />{activeTab === 'basic' && <div className="appointment-settings-form">
      <div className="appointment-settings-row"><label><span className="required-label">*</span>门店可预约时间</label><Space.Compact><TimePicker value={timeValue(settings.businessStart, '09:00')} format="HH:mm" onChange={value => patch('businessStart', value?.format('HH:mm') ?? settings.businessStart)} /><span className="appointment-settings-to">至</span><TimePicker value={timeValue(settings.businessEnd, '19:30')} format="HH:mm" onChange={value => patch('businessEnd', value?.format('HH:mm') ?? settings.businessEnd)} /></Space.Compact></div>
      <div className="appointment-settings-row appointment-settings-staff"><label><span className="required-label">*</span>门店可预约员工</label><Select mode="multiple" value={settings.bookableStaffIds} onChange={value => patch('bookableStaffIds', value as number[])} options={staffOptions.filter(item => item.id > 0).map(item => ({ value: item.id, label: item.name }))} placeholder="请选择可预约技师" /></div>
      <div className="appointment-settings-row"><label><span className="required-label">*</span>开启公众号预约</label><Switch checked={settings.publicBookingEnabled} onChange={value => patch('publicBookingEnabled', value)} /><span className="appointment-settings-hint">用户可以在公众号里预约，需先配置公众号功能。</span></div>
      <div className="appointment-settings-row"><label>公众号预约图</label><Upload accept=".png,.jpg,.jpeg,.webp" showUploadList={false} beforeUpload={file => readImage(file as File)}><Button icon={<UploadOutlined />}>上传图片</Button></Upload>{settings.publicImageData && <img className="appointment-public-image-preview" src={settings.publicImageData} alt="公众号预约图" />}</div>
      <div className="appointment-settings-row appointment-settings-block"><label><span className="required-label">*</span>公众号可预约时间段</label><div className="appointment-slot-list">{settings.publicSlots.map((slot, index) => <div className="appointment-slot-row" key={`${index}-${slot.start}`}><TimePicker value={timeValue(slot.start, settings.businessStart)} format="HH:mm" onChange={value => patch('publicSlots', settings.publicSlots.map((item, itemIndex) => itemIndex === index ? { ...item, start: value?.format('HH:mm') ?? item.start } : item))} /><span>至</span><TimePicker value={timeValue(slot.end, settings.businessEnd)} format="HH:mm" onChange={value => patch('publicSlots', settings.publicSlots.map((item, itemIndex) => itemIndex === index ? { ...item, end: value?.format('HH:mm') ?? item.end } : item))} /><Button type="text" danger icon={<DeleteOutlined />} aria-label="删除时间段" onClick={() => patch('publicSlots', settings.publicSlots.filter((_, slotIndex) => slotIndex !== index))} /></div>)}<Button onClick={() => patch('publicSlots', [...settings.publicSlots, { start: settings.businessStart, end: settings.businessEnd }])}>添加时段</Button></div></div>
      <div className="appointment-settings-row appointment-settings-block"><label><span className="required-label">*</span>公众号开放预约日期</label><Checkbox.Group value={settings.publicWeekdays} onChange={value => patch('publicWeekdays', value as number[])} options={[{ value: 1, label: '周一' }, { value: 2, label: '周二' }, { value: 3, label: '周三' }, { value: 4, label: '周四' }, { value: 5, label: '周五' }, { value: 6, label: '周六' }, { value: 7, label: '周日' }]} /><div className="appointment-closed-date-row"><DatePicker value={closedDate} onChange={value => setClosedDate(value ?? undefined)} placeholder="选择不开放日期" /><Button onClick={addClosedDate}>添加不开放日期</Button>{settings.closedDates.map(value => <Tag closable key={value} onClose={() => patch('closedDates', settings.closedDates.filter(date => date !== value))}>{value}</Tag>)}</div></div>
      <div className="appointment-settings-row appointment-settings-select-row"><label><span className="required-label">*</span>需要提前预约时间</label><Select value={settings.advanceMinutes} onChange={value => patch('advanceMinutes', value)} options={[{ value: 0, label: '不限制' }, { value: 60, label: '60分钟' }, { value: 120, label: '120分钟' }, { value: 240, label: '240分钟' }]} /></div><div className="appointment-settings-row appointment-settings-select-row"><label>预约时间间隔默认时间</label><Select value={settings.intervalMinutes} onChange={value => patch('intervalMinutes', value)} options={[{ value: 10, label: '10分钟' }, { value: 20, label: '20分钟' }, { value: 30, label: '30分钟' }, { value: 60, label: '60分钟' }]} /></div><div className="appointment-settings-row appointment-settings-select-row"><label>最多可提前预约天数</label><Select value={settings.maxAdvanceDays} onChange={value => patch('maxAdvanceDays', value)} options={[7, 15, 30, 60, 90].map(value => ({ value, label: `${value}天` }))} /></div>
    </div>}{activeTab === 'advanced' && <div className="appointment-settings-advanced"><div className="appointment-settings-row"><label>开启资源冲突校验</label><Switch checked={settings.preventConflicts} onChange={value => patch('preventConflicts', value)} /></div><p>开启后，同一技师或同一房间在重叠时间段内不能重复创建预约；关闭后允许保存重叠安排。</p></div>}</div>}
  </Drawer>
}

function AppointmentListView({ tenantId, departmentId, revision, writable, onEdit, onDelete }: { tenantId?: number; departmentId?: number; revision: number; writable: boolean; onEdit: (appointment: Appointment) => void; onDelete: (appointment: Appointment) => void }) {
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [searchBy, setSearchBy] = useState('NAME'); const [status, setStatus] = useState<AppointmentStatus | 'ALL'>('ALL'); const [range, setRange] = useState<[Dayjs, Dayjs]>([dayjs(), dayjs()])
  const path = `/appointments?startDate=${range[0].format('YYYY-MM-DD')}&endDate=${range[1].format('YYYY-MM-DD')}&page=${page}&pageSize=10${departmentId ? `&departmentId=${departmentId}` : ''}${keyword ? `&keyword=${encodeURIComponent(keyword)}&searchBy=${searchBy}` : ''}${status === 'ALL' ? '' : `&status=${status}`}`
  const query = useCatalogQuery<PageResult<Record<string, unknown>>>(path, tenantId, revision, Boolean(departmentId)); const records = useMemo(() => (query.data?.records ?? []).map(toAppointment), [query.data])
  const columns = [{ title: '顾客信息', key: 'customer', render: (_: unknown, row: Appointment) => <div className="appointment-list-customer"><strong>{row.customer || '临时占用'}</strong><span>{row.phone || '-'}</span></div> }, { title: '日期', dataIndex: 'date', key: 'date' }, { title: '时间/技师', key: 'time', render: (_: unknown, row: Appointment) => <span>{row.start} / {row.staff || '-'}</span> }, { title: '项目', dataIndex: 'service', key: 'service', render: (value: string) => value || '-' }, { title: '房间', dataIndex: 'room', key: 'room', render: (value: string) => value || '-' }, { title: '状态', key: 'status', render: (_: unknown, row: Appointment) => <Tag color={row.color}>{statusMeta(row.status).label}</Tag> }, { title: '备注', dataIndex: 'note', key: 'note', render: (value: string) => value || '-' }, { title: '创建时间', key: 'createdAt', render: (_: unknown, row: Appointment) => formatDateTime(row.createdAt) }, { title: '编辑时间', key: 'updatedAt', render: (_: unknown, row: Appointment) => formatDateTime(row.updatedAt) }, { title: '操作', key: 'actions', fixed: 'right' as const, render: (_: unknown, row: Appointment) => <Space><Button type="link" disabled={!writable} onClick={() => onEdit(row)}>编辑</Button><Button type="link" danger disabled={!writable} onClick={() => onDelete(row)}>删除</Button></Space> }]
  return <section className="appointment-list-view"><div className="appointment-list-toolbar"><Space wrap><Space.Compact><Select value={searchBy} onChange={setSearchBy} options={[{ value: 'NAME', label: '顾客' }, { value: 'PHONE', label: '手机号' }, { value: 'ID', label: '预约编号' }]} /><Input.Search value={keyword} allowClear placeholder="输入顾客姓名/手机号/编号" onChange={event => setKeyword(event.target.value)} onSearch={() => setPage(1)} /></Space.Compact><DatePicker.RangePicker value={range} allowClear={false} format="YYYY/MM/DD" onChange={value => { if (value?.[0] && value[1]) { setRange([value[0], value[1]]); setPage(1) } }} /><Select value={status} onChange={value => { setStatus(value); setPage(1) }} options={[{ value: 'ALL', label: '全部预约' }, ...statuses.map(item => ({ value: item.value, label: item.label }))]} /></Space></div><Table<Appointment> rowKey="id" loading={query.loading} columns={columns} dataSource={records} scroll={{ x: 1320 }} pagination={{ current: page, pageSize: 10, total: query.data?.total ?? 0, onChange: setPage, showSizeChanger: false }} locale={{ emptyText: query.loading ? <Spin /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无相关数据" /> }} /></section>
}

export default function AppointmentPage() {
  const { session, can } = useAuth(); const platform = session?.userInfo.platformAdmin ?? false; const [params, setParams] = useSearchParams(); const rawTenant = platform ? params.get('tenantId') : null; const tenantId = rawTenant === null ? undefined : Number(rawTenant); const enabled = platform ? tenantId !== undefined : true; const { message, modal } = App.useApp()
  const customerId = params.get('customerId'); const [customerPrefill, setCustomerPrefill] = useState<{ customer: string; phone: string }>(); const [date, setDate] = useState<Dayjs>(dayjs()); const [viewMode, setViewMode] = useState<ViewMode>('staff'); const [displayMode, setDisplayMode] = useState<DisplayMode>('calendar'); const [departmentId, setDepartmentId] = useState<number>(); const [statusFilter, setStatusFilter] = useState<AppointmentStatus | 'ALL'>('ALL'); const [revision, setRevision] = useState(0); const [panel, setPanel] = useState<'size' | 'settings' | null>(null); const [calendarHeight, setCalendarHeight] = useState(640); const [columnWidth, setColumnWidth] = useState(180); const [operationOpen, setOperationOpen] = useState(false); const [operationType, setOperationType] = useState<OperationType>('NORMAL'); const [editor, setEditor] = useState<{ open: boolean; appointment?: Appointment; start: string; operationType: OperationType }>({ open: false, start: '10:00', operationType: 'NORMAL' })
  const customerQuery = useCatalogQuery<CustomerPrefillRecord>(customerId ? `/customers/${encodeURIComponent(customerId)}` : '/customers/0', tenantId, 0, Boolean(customerId && enabled))
  const departments = useCatalogQuery<Department[]>('/iam/departments', tenantId, revision, enabled); const options = useCatalogQuery<{ staff?: Array<Record<string, unknown>>; rooms?: Array<Record<string, unknown>>; services?: Array<Record<string, unknown>> }>(`/appointments/options${departmentId ? `?departmentId=${departmentId}` : ''}`, tenantId, revision, enabled); const query = useCatalogQuery<PageResult<Record<string, unknown>>>(`/appointments?date=${date.format('YYYY-MM-DD')}&page=1&pageSize=100${departmentId ? `&departmentId=${departmentId}` : ''}${statusFilter === 'ALL' ? '' : `&status=${statusFilter}`}`, tenantId, revision, enabled)
  const stores = (departments.data ?? []).filter(item => item.type === 'STORE' && item.status === 1); const store = stores.find(item => item.id === departmentId) ?? stores[0]; const staffOptions = useMemo(() => [{ id: 0, name: '未选择' }, ...resourceOptions(options.data?.staff, defaultStaffColumns, 'staff')], [options.data]); const roomOptions = useMemo(() => [{ id: 0, name: '未选择房间' }, ...resourceOptions(options.data?.rooms, defaultRoomColumns, 'room')], [options.data]); const serviceOptions = useMemo(() => { const values = (options.data?.services ?? []).map(row => String(row.name ?? '')).filter(Boolean); return values.length ? values : defaultServices }, [options.data]); const appointments = useMemo(() => (query.data?.records ?? []).map(toAppointment), [query.data]); const columns = viewMode === 'staff' ? staffOptions : roomOptions; const counts = useMemo(() => statuses.map(status => ({ ...status, count: appointments.filter(item => item.status === status.value).length })), [appointments]); const writable = platform || can('appointments:write'); const rowHeight = calendarHeight / slots.length; const calendarStyle = { '--appointment-columns': columns.length, '--appointment-column-width': `${columnWidth}px`, '--appointment-board-height': `${calendarHeight}px`, '--appointment-row-height': `${rowHeight}px` } as CSSProperties
  useEffect(() => {
    if (!customerId || customerPrefill || editor.open || customerQuery.loading) return
    if (customerQuery.error) {
      void message.error(`无法加载顾客预约信息：${customerQuery.error}`)
      setParams(current => { current.delete('customerId'); return current }, { replace: true })
      return
    }
    const phone = customerQuery.data?.phone?.trim() ?? ''
    setCustomerPrefill({ customer: phone ? maskCustomerPhone(phone) : customerQuery.data?.name?.trim() || '顾客', phone })
    if (customerQuery.data?.storeId) setDepartmentId(customerQuery.data.storeId)
    setEditor({ open: true, start: '14:00', operationType: 'NORMAL' })
    setParams(current => { current.delete('customerId'); return current }, { replace: true })
  }, [customerId, customerPrefill, customerQuery.data, customerQuery.error, customerQuery.loading, editor.open, message, setParams])
  useEffect(() => { if (departmentId === undefined && stores[0]) setDepartmentId(stores[0].id) }, [departmentId, stores])
  function changeDate(next: Dayjs) { setDate(next); setStatusFilter('ALL') } function openNew(start = '10:00') { setCustomerPrefill(undefined); setOperationType('NORMAL'); setOperationOpen(true); setEditor(current => ({ ...current, start, appointment: undefined })) } function confirmOperation() { setOperationOpen(false); setEditor(current => ({ ...current, open: true, operationType })) } function openEdit(appointment: Appointment) { setCustomerPrefill(undefined); setEditor({ open: true, appointment, start: appointment.start, operationType: appointment.bookingType }) }
  async function save(values: AppointmentFormValues) {
    if (!store) { void message.warning('请先配置门店'); return }
    const type = editor.operationType; const selectedStaff = values.staff && !isUnassignedResource(values.staff, 'staff') ? values.staff : ''; const selectedRoom = values.room && !isUnassignedResource(values.room, 'room') ? values.room : ''; const staffName = selectedStaff || (viewMode === 'staff' && !isUnassignedResource(columns[0]?.name, 'staff') ? columns[0].name : ''); const roomName = selectedRoom || (viewMode === 'room' && !isUnassignedResource(columns[0]?.name, 'room') ? columns[0].name : ''); const payload = { departmentId: store.id, appointmentDate: values.date.format('YYYY-MM-DD'), startTime: values.start.format('HH:mm:ss'), durationMinutes: values.duration, customerName: values.customer.trim() || (type === 'TEMP_BLOCK' ? '临时占用' : ''), phone: values.phone?.trim(), serviceName: values.service.trim() || (type === 'TEMP_BLOCK' ? '时间占用' : ''), staffName, roomName, status: type === 'TEMP_BLOCK' ? 'TEMP_BLOCK' : customerPrefill ? (values.confirmed ? 'CONFIRMED' : 'PENDING') : values.status, color: values.color, note: values.note?.trim(), partySize: values.partySize, needsTea: values.needsTea, needsAirConditioner: values.needsAirConditioner, bringsPet: values.bringsPet, bringsChild: values.bringsChild, needsBath: values.needsBath, bookingType: type }
    try { if (type === 'RECURRING' && !editor.appointment) await catalogRequest('/appointments/recurring', tenantId, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ appointment: payload, occurrences: values.occurrences ?? 4 }) }); else await catalogRequest(`/appointments${editor.appointment ? `/${editor.appointment.id}` : ''}`, tenantId, { method: editor.appointment ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); setEditor(current => ({ ...current, open: false, appointment: undefined })); setCustomerPrefill(undefined); setRevision(value => value + 1); void message.success(type === 'RECURRING' ? '长期预约已创建' : editor.appointment ? '预约已更新' : '创建预约成功') } catch (cause) { void message.error(cause instanceof Error ? cause.message : '保存失败，请重试') }
  }
  function remove(appointment: Appointment) { modal.confirm({ title: `删除“${appointment.customer || '临时占用'}”预约？`, content: '删除后不可恢复。', okText: '删除', okButtonProps: { danger: true }, cancelText: '取消', onOk: async () => { try { await catalogRequest(`/appointments/${appointment.id}`, tenantId, { method: 'DELETE' }); setRevision(value => value + 1); void message.success('预约已删除') } catch (cause) { void message.error(cause instanceof Error ? cause.message : '删除失败，请重试'); throw cause } } }) }
  if (!platform && !can('appointments:read')) return <Result status="403" title="暂无预约管理权限" />
  if (platform && tenantId === undefined) return <div className="appointment-page"><EnterpriseSelector value={tenantId} onChange={id => setParams(current => { if (id === undefined) current.delete('tenantId'); else current.set('tenantId', String(id)); return current })} /><section className="catalog-panel appointment-scope-prompt"><Result status="info" title="请选择要管理的企业" subTitle="预约数据按企业和门店独立维护。" /></section></div>
  return <div className="appointment-page">{platform && <EnterpriseSelector value={tenantId} onChange={id => setParams(current => { if (id === undefined) current.delete('tenantId'); else current.set('tenantId', String(id)); return current })} />}<QueryError error={query.error || departments.error || options.error} onRetry={() => { query.reload(); departments.reload(); options.reload() }} />
    {panel === 'size' && <section className="appointment-size-panel"><strong>调整预约表尺寸</strong><label>高度：<Slider min={480} max={900} value={calendarHeight} onChange={value => setCalendarHeight(Number(value))} /></label><label>宽度：<Slider min={140} max={320} value={columnWidth} onChange={value => setColumnWidth(Number(value))} /></label><Button type="primary" onClick={() => { setPanel(null); void message.success('预约表尺寸已更新') }}>确认</Button></section>}
    <div className="appointment-toolbar"><div className="appointment-toolbar-left"><div className="appointment-date-control"><Button type="text" icon={<LeftOutlined />} aria-label="前一天" onClick={() => changeDate(date.subtract(1, 'day'))} /><DatePicker bordered={false} value={date} allowClear={false} format="YYYY-MM-DD dddd" onChange={value => value && changeDate(value)} /><Button type="text" icon={<RightOutlined />} aria-label="后一天" onClick={() => changeDate(date.add(1, 'day'))} /><Button size="small" onClick={() => changeDate(dayjs())}>今天</Button></div><Radio.Group className="appointment-dimension-switch" value={viewMode} onChange={event => setViewMode(event.target.value)} optionType="button" buttonStyle="solid" options={[{ value: 'staff', label: '技师维度' }, { value: 'room', label: '房间维度' }]} /></div><div className="appointment-toolbar-actions"><Select value={store?.id} onChange={value => { setDepartmentId(value); setRevision(current => current + 1) }} loading={departments.loading} options={stores.map(value => ({ value: value.id, label: value.name }))} placeholder="请选择门店" aria-label="选择门店" /><Select value={statusFilter} onChange={setStatusFilter} options={[{ value: 'ALL', label: '全部状态' }, ...statuses.map(item => ({ value: item.value, label: item.label }))]} aria-label="筛选预约状态" /><div className="appointment-quick-actions"><Tooltip title="调整预约表尺寸"><Button icon={<ExpandOutlined />} aria-label="调整预约表尺寸" onClick={() => setPanel('size')} /></Tooltip><Tooltip title="预约设置"><Button icon={<SettingOutlined />} aria-label="预约设置" onClick={() => setPanel('settings')} /></Tooltip><Tooltip title={displayMode === 'calendar' ? '列表视图' : '日历视图'}><Button icon={displayMode === 'calendar' ? <UnorderedListOutlined /> : <CalendarOutlined />} aria-label="切换预约视图" onClick={() => setDisplayMode(current => current === 'calendar' ? 'list' : 'calendar')} /></Tooltip></div><Button type="primary" icon={<PlusOutlined />} disabled={!writable || !store} onClick={() => openNew()}>新增预约</Button></div></div>
    {displayMode === 'list' ? <AppointmentListView tenantId={tenantId} departmentId={store?.id} revision={revision} writable={writable} onEdit={openEdit} onDelete={remove} /> : <><section className="appointment-summary-card" aria-label="预约概览"><div className="appointment-summary-copy"><span className="appointment-summary-eyebrow">{store?.name ?? '未选择门店'}</span><strong>{date.format('YYYY年MM月DD日 dddd')}</strong><span>今日营业预约一览</span></div><div className="appointment-summary-stats">{counts.map(item => <button type="button" className="appointment-summary-stat" key={item.value} onClick={() => setStatusFilter(current => current === item.value ? 'ALL' : item.value)}><span className="appointment-summary-dot" style={{ background: item.color }} /><strong>{item.count}</strong><span>{item.label}</span></button>)}</div></section>
       <section className="appointment-board" aria-label="预约日历" style={calendarStyle}><div className="appointment-board-header"><div className="appointment-board-title"><ClockCircleOutlined /><span>预约日历</span><Tag color="blue">{appointments.length} 条安排</Tag></div><Button type="link" icon={<PlusOutlined />} disabled={!writable || !store} onClick={() => openNew()}>快速新增</Button></div><div className="appointment-grid-header"><div className="appointment-grid-corner"><span>时间</span></div>{columns.map(column => <div className="appointment-grid-column-title" key={column.id}><span className="appointment-avatar">{viewMode === 'staff' ? <UserOutlined /> : <AppstoreOutlined />}</span><div><strong>{column.name}</strong><small>{column.id === 0 ? '未指定资源' : viewMode === 'staff' ? '可预约' : '空闲房间'}</small></div></div>)}</div><div className="appointment-grid-body"><div className="appointment-time-axis">{slots.map(slot => <div key={slot}>{slot}</div>)}</div>{columns.map(column => <div className="appointment-grid-column" key={column.id}>{slots.map(slot => <button type="button" className="appointment-grid-cell" key={`${column.id}-${slot}`} aria-label={`${column.name} ${slot} 新增预约`} disabled={!writable || !store} onClick={() => openNew(slot)} />)}{appointments.filter(item => { const resource = viewMode === 'staff' ? item.staff : item.room; return column.id === 0 ? isUnassignedResource(resource, viewMode) : resource === column.name }).map(item => <Popover key={item.id} content={eventDetail(item, viewMode)} trigger="hover" placement="right"><div className="appointment-event-shell" style={{ top: `${minutesOf(item.start) * (rowHeight / 60)}px`, height: `${Math.max(36, item.duration * (rowHeight / 60) - 8)}px` }}><div className="appointment-event" role="button" tabIndex={0} style={{ borderLeftColor: item.color }} onClick={() => openEdit(item)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') openEdit(item) }}><span className="appointment-event-time">{item.start} · {item.duration}分钟</span><strong>{item.customer || '临时占用'}</strong><span>{item.service || '时间占用'}</span><small>{viewMode === 'staff' ? item.room : item.staff} · {statusMeta(item.status).label}</small><span className="appointment-event-delete" role="button" aria-label={`删除${item.customer}预约`} onClick={event => { event.stopPropagation(); remove(item) }}><DeleteOutlined /></span></div></div></Popover>)}</div>)}</div>{query.loading && <div className="appointment-loading-overlay"><Spin /></div>}{!query.loading && appointments.length === 0 && <div className="appointment-empty-overlay"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前筛选条件下暂无预约" /><Button type="primary" disabled={!writable || !store} onClick={() => openNew()}>新增第一条预约</Button></div>}</section><div className="appointment-footnote"><CheckCircleOutlined /> 预约已接入企业数据，保存后可在门店端同步查看。</div></>}
    <OperationChooser open={operationOpen} value={operationType} onChange={setOperationType} onCancel={() => setOperationOpen(false)} onConfirm={confirmOperation} /><AppointmentSettingsDrawer open={panel === 'settings'} tenantId={tenantId} departmentId={store?.id} staffOptions={staffOptions} onClose={() => setPanel(null)} onSaved={() => setRevision(value => value + 1)} /><AppointmentEditor open={editor.open} appointment={editor.appointment} customerPrefill={customerPrefill} defaultStart={editor.start} defaultDate={date} viewMode={viewMode} operationType={editor.operationType} staffOptions={staffOptions} roomOptions={roomOptions} serviceOptions={serviceOptions} onClose={() => { setEditor(current => ({ ...current, open: false })); setCustomerPrefill(undefined) }} onSave={save} />
  </div>
}
