import { useState } from 'react'
import dayjs, { type Dayjs } from 'dayjs'
import { App, Button, DatePicker, Form, Input, InputNumber, Modal, Pagination, Result, Select, Space, Spin, Switch, Table, Tabs, Tag, Upload } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { DownloadOutlined, FileAddOutlined, PlusOutlined, ReloadOutlined, SwapOutlined } from '@ant-design/icons'
import { useSearchParams } from 'react-router-dom'
import { errorMessage, QueryError, paginationOptions } from '@/components/iam/shared'
import { useAuth } from '@/context/AuthContext'
import { catalogRequest, useCatalogQuery } from '@/api/catalog'
import type { Department, PageResult } from '@/types/iam'
import type { CatalogItem, InventoryAccountRow, InventoryBatchRow, InventoryChangeRow, InventoryChangeType, InventoryDocumentRow, InventoryDocumentStatus, InventoryDocumentType, InventoryRow } from '@/types/catalog'
import '@/styles/catalog.css'

export const inventoryTabs = [
  { key: 'stock', label: '库存查询' },
  { key: 'changes', label: '出入明细' },
  { key: 'batch', label: '批次管理' },
  { key: 'liquidation', label: '库存盘点' },
  { key: 'call', label: '调拨管理' },
  { key: 'account', label: '成本核算' },
  { key: 'settings', label: '库存设置' },
] as const
type InventoryView = typeof inventoryTabs[number]['key']

function money(value: number | string | undefined) { return value === undefined ? '—' : `¥${Number(value).toFixed(2)}` }
function date(value?: string) { return value ? value.replace('T', ' ').slice(0, 16) : '—' }
function departmentOptions(departments: Department[]) { return departments.filter(item => item.type === 'STORE' && item.status === 1).map(item => ({ value: item.id, label: item.name })) }
function productOptions(products: CatalogItem[]) { return products.filter(item => item.status === 1).map(item => ({ value: item.id, label: `${item.name} · ${item.code}` })) }

function InventoryChangeForm({ open, tenantId, departments, products, initialType = 'IN', onClose, onSaved }: { open: boolean; tenantId?: number; departments: Department[]; products: CatalogItem[]; initialType?: InventoryChangeType; onClose: () => void; onSaved: () => void }) {
  const [form] = Form.useForm(); const [saving, setSaving] = useState(false); const { message } = App.useApp(); const changeType = Form.useWatch('changeType', form) as InventoryChangeType | undefined
  const submit = async (values: Record<string, unknown>) => { setSaving(true); try { await catalogRequest('/inventory/changes', tenantId, { method: 'POST', body: JSON.stringify(values) }); void message.success('库存流水已登记'); onSaved(); onClose(); form.resetFields() } catch (cause) { void message.error(errorMessage(cause)) } finally { setSaving(false) } }
  return <Modal className="catalog-modal" width={560} centered title={initialType === 'IN' ? '产品入库' : initialType === 'OUT' ? '产品出库' : '登记库存变更'} open={open} onCancel={onClose} destroyOnClose footer={null} afterOpenChange={visible => { if (visible) form.setFieldsValue({ changeType: initialType, quantity: 1, unitCost: 0, warningValue: 0 }) }}><Form form={form} layout="vertical" onFinish={submit} initialValues={{ changeType: initialType, quantity: 1, unitCost: 0, warningValue: 0 }}><Form.Item name="departmentId" label="门店 / 部门" rules={[{ required: true, message: '请选择门店' }]}><Select options={departmentOptions(departments)} /></Form.Item><Form.Item name="itemId" label="产品" rules={[{ required: true, message: '请选择产品' }]}><Select showSearch optionFilterProp="label" options={productOptions(products)} /></Form.Item><Form.Item name="changeType" label="流水类型"><Select options={[{ value: 'IN', label: '入库' }, { value: 'OUT', label: '出库' }, { value: 'ADJUST', label: '盘点调整（填写盘后数量）' }]} /></Form.Item><Space className="catalog-form-row" align="start"><Form.Item name="quantity" label={changeType === 'ADJUST' ? '盘后数量' : '数量'} rules={[{ required: true }]}><InputNumber min={0.001} precision={3} /></Form.Item><Form.Item name="unitCost" label="单位成本" rules={[{ required: true }]}><InputNumber min={0} precision={2} /></Form.Item><Form.Item name="warningValue" label="库存预警线" rules={[{ required: true }]}><InputNumber min={0} precision={3} /></Form.Item></Space><Form.Item name="referenceNo" label="单据号"><Input maxLength={80} /></Form.Item><Form.Item name="reason" label="原因 / 备注"><Input.TextArea maxLength={300} rows={3} /></Form.Item><div className="catalog-dialog-actions"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={saving}>登记</Button></div></Form></Modal>
}

function InventoryDocumentForm({ open, tenantId, departments, initialType = 'LIQUIDATION', onClose, onSaved }: { open: boolean; tenantId?: number; departments: Department[]; initialType?: InventoryDocumentType; onClose: () => void; onSaved: () => void }) {
  const [form] = Form.useForm(); const [saving, setSaving] = useState(false); const { message } = App.useApp();
  const submit = async (values: Record<string, unknown>) => { setSaving(true); try { await catalogRequest('/inventory/documents', tenantId, { method: 'POST', body: JSON.stringify({ ...values, documentDate: (values.documentDate as Dayjs).format('YYYY-MM-DD') }) }); void message.success('单据已创建'); onSaved(); onClose(); form.resetFields() } catch (cause) { void message.error(errorMessage(cause)) } finally { setSaving(false) } }
  const options = departmentOptions(departments)
  return <Modal className="catalog-modal" width={560} centered title={initialType === 'LIQUIDATION' ? '新建库存盘点单' : initialType === 'TRANSFER_IN' ? '新建调拨入库' : '新建调拨出库'} open={open} onCancel={onClose} destroyOnClose footer={null} afterOpenChange={visible => { if (visible) form.setFieldsValue({ docType: initialType, documentDate: dayjs(), status: 'DRAFT' }) }}><Form form={form} layout="vertical" onFinish={submit} initialValues={{ docType: initialType, documentDate: dayjs(), status: 'DRAFT' }}><Form.Item name="docType" hidden><Input /></Form.Item>{initialType === 'TRANSFER_IN' && <Form.Item name="targetDepartmentId" label="调入仓库" rules={[{ required: true, message: '请选择调入门店' }]}><Select options={options} /></Form.Item>}{initialType === 'TRANSFER_OUT' && <Form.Item name="sourceDepartmentId" label="调出仓库" rules={[{ required: true, message: '请选择调出门店' }]}><Select options={options} /></Form.Item>}{initialType === 'LIQUIDATION' && <Form.Item name="sourceDepartmentId" label="仓库 / 门店"><Select allowClear options={options} /></Form.Item>}<Space className="catalog-form-row" align="start"><Form.Item name="documentNo" label="单据号"><Input maxLength={80} placeholder="不填写则自动生成" /></Form.Item><Form.Item name="documentDate" label="日期" rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} /></Form.Item></Space><Space className="catalog-form-row" align="start"><Form.Item name="operatorName" label="经办人"><Input maxLength={80} /></Form.Item><Form.Item name="status" label="状态"><Select options={[{ value: 'DRAFT', label: '草稿' }, { value: 'PENDING', label: '待处理' }, { value: 'CONFIRMED', label: '已确认' }]} /></Form.Item></Space><Form.Item name="remark" label="备注"><Input.TextArea rows={3} maxLength={300} /></Form.Item><div className="catalog-dialog-actions"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={saving}>保存</Button></div></Form></Modal>
}

function InventoryCsvImport({ open, tenantId, onClose, onSaved }: { open: boolean; tenantId?: number; onClose: () => void; onSaved: () => void }) {
  const { message } = App.useApp(); const [uploading, setUploading] = useState(false)
  async function importFile(file: File) {
    setUploading(true)
    try {
      const text = await file.text(); const rows = text.split(/\r?\n/).map(row => row.trim()).filter(Boolean).slice(1)
      for (const row of rows) {
        const [documentNo, documentDate, operatorName, remark] = row.split(',').map(value => value.trim())
        if (!documentDate) continue
        await catalogRequest('/inventory/documents', tenantId, { method: 'POST', body: JSON.stringify({ docType: 'LIQUIDATION', documentNo, documentDate, operatorName, status: 'DRAFT', remark }) })
      }
      void message.success('库存盘点单已导入'); onSaved(); onClose()
    } catch (cause) { void message.error(errorMessage(cause)) } finally { setUploading(false) }
    return Upload.LIST_IGNORE
  }
  return <Modal className="catalog-modal" width={480} centered title="导入库存盘点单" open={open} onCancel={onClose} footer={null}><p className="inventory-import-hint">CSV 首行为表头，后续按“单据号,日期,经办人,备注”填写。</p><Upload accept=".csv,.txt" maxCount={1} showUploadList={false} beforeUpload={importFile}><Button type="primary" icon={<FileAddOutlined />} loading={uploading}>选择文件</Button></Upload></Modal>
}

function StockWorkspace({ tenantId, platform, departments, products, revision, setRevision, onOpenChange, onEditWarning }: { tenantId?: number; platform: boolean; departments: Department[]; products: CatalogItem[]; revision: number; setRevision: (value: (current: number) => number) => void; onOpenChange: (type: InventoryChangeType) => void; onEditWarning: (row: InventoryRow) => void }) {
  const { can } = useAuth(); const { message } = App.useApp(); const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [brand, setBrand] = useState<string>(); const [category, setCategory] = useState<string>(); const [departmentId, setDepartmentId] = useState<number>(); const [shortageOnly, setShortageOnly] = useState(false)
  const query = useCatalogQuery<PageResult<InventoryRow>>(`/inventory?page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${brand ? `&brand=${encodeURIComponent(brand)}` : ''}${category ? `&category=${encodeURIComponent(category)}` : ''}${departmentId ? `&departmentId=${departmentId}` : ''}&shortageOnly=${shortageOnly}`, tenantId, revision, platform ? tenantId !== undefined : true)
  const rows = query.data?.records ?? []
  const lowStock = rows.filter(row => row.shortage === 1 || row.quantity <= row.warningValue).length; const stockTotal = rows.reduce((sum, row) => sum + Number(row.quantity || 0), 0)
  const categories = [...new Set(products.map(item => item.category).filter(Boolean))] as string[]; const brands = [...new Set(products.map(item => item.brand).filter(Boolean))] as string[]
  const columns: ColumnsType<InventoryRow> = [
    { title: '产品信息', key: 'item', width: 250, render: (_: unknown, row) => <div className="catalog-cell-stack"><strong>{row.itemName}</strong><span>{row.itemCode} · {row.spec || row.unit || '—'}</span></div> },
    { title: '所属仓库', dataIndex: 'departmentName', width: 180 }, { title: '库存数量', dataIndex: 'quantity', width: 110, render: (value: number, row) => <strong className={row.shortage === 1 || value <= row.warningValue ? 'catalog-warning' : ''}>{value}</strong> },
    { title: '单位', dataIndex: 'unit', width: 80, render: value => value || '—' }, { title: '产品品牌', dataIndex: 'brand', width: 120, render: value => value || '—' }, { title: '产品品类', dataIndex: 'category', width: 120, render: value => value || '—' },
    { title: '产品价格', dataIndex: 'costPrice', width: 110, render: money }, { title: '库存下限', dataIndex: 'warningValue', width: 100 },
    { title: '操作', key: 'actions', width: 260, render: (_: unknown, row) => <Space wrap size={0}><Button type="link" onClick={() => onOpenChange('ADJUST')}>库存明细</Button><Button type="link" onClick={() => onOpenChange('IN')}>保质期明细</Button><Button type="link" onClick={() => onOpenChange('OUT')}>批次明细</Button><Button type="link" disabled={!platform && !can('inventory:write')} onClick={() => onEditWarning(row)}>修改库存下限</Button></Space> },
  ]
  return <><div className="inventory-summary"><div><span>库存品项</span><strong>{query.data?.total ?? 0}</strong><small>当前页记录</small></div><div><span>库存总量</span><strong>{stockTotal.toFixed(2)}</strong><small>按当前页汇总</small></div><div className={lowStock ? 'is-warning' : ''}><span>库存预警</span><strong>{lowStock}</strong><small>{lowStock ? '需要及时补货' : '暂无预警'}</small></div></div><div className="inventory-action-bar"><Space wrap><Button type="primary" icon={<SwapOutlined />} disabled={!platform && !can('inventory:write')} onClick={() => onOpenChange('OUT')}>产品出库</Button><Button type="primary" icon={<SwapOutlined />} disabled={!platform && !can('inventory:write')} onClick={() => onOpenChange('IN')}>产品入库</Button><Button icon={<DownloadOutlined />} onClick={() => void message.info('请先按筛选条件查询后导出库存表')}>报表下载</Button></Space></div><div className="inventory-filter-row"><Select allowClear placeholder="全部门店" value={departmentId} onChange={value => { setDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear placeholder="请选择品牌" value={brand} onChange={value => { setBrand(value); setPage(1) }} options={brands.map(value => ({ value, label: value }))} /><Select allowClear placeholder="请选择分类" value={category} onChange={value => { setCategory(value); setPage(1) }} options={categories.map(value => ({ value, label: value }))} /><Input.Search aria-label="搜索库存" placeholder="请输入产品名称/编号" allowClear onSearch={value => { setKeyword(value.trim()); setPage(1) }} /><Space size={6}><Switch checked={shortageOnly} onChange={checked => { setShortageOnly(checked); setPage(1) }} /><span>只看库存不足</span></Space><Button icon={<ReloadOutlined />} aria-label="刷新库存" onClick={() => setRevision(value => value + 1)} /></div><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryRow> rowKey="id" loading={query.loading} columns={columns} dataSource={rows} scroll={{ x: 1320 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无库存记录' }} /><div className="catalog-footer"><span>共 {query.data?.total ?? 0} 条</span><Pagination {...paginationOptions} current={page} pageSize={10} total={query.data?.total ?? 0} onChange={setPage} /></div></>
}

function ChangeWorkspace({ tenantId, platform, departments, products, revision, setRevision, onOpenChange }: { tenantId?: number; platform: boolean; departments: Department[]; products: CatalogItem[]; revision: number; setRevision: (value: (current: number) => number) => void; onOpenChange: (type: InventoryChangeType) => void }) {
  const { message } = App.useApp(); const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [brand, setBrand] = useState<string>(); const [category, setCategory] = useState<string>(); const [departmentId, setDepartmentId] = useState<number>(); const [itemId, setItemId] = useState<number>(); const [types, setTypes] = useState<InventoryChangeType[]>([]); const [range, setRange] = useState<[Dayjs, Dayjs]>();
  const query = useCatalogQuery<PageResult<InventoryChangeRow>>(`/inventory/changes?page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${brand ? `&brand=${encodeURIComponent(brand)}` : ''}${category ? `&category=${encodeURIComponent(category)}` : ''}${departmentId ? `&departmentId=${departmentId}` : ''}${itemId ? `&itemId=${itemId}` : ''}${types.length ? `&changeType=${types.join(',')}` : ''}${range ? `&startDate=${range[0].format('YYYY-MM-DD')}&endDate=${range[1].format('YYYY-MM-DD')}` : ''}`, tenantId, revision, platform ? tenantId !== undefined : true)
  const brands = [...new Set(products.map(item => item.brand).filter(Boolean))] as string[]; const categories = [...new Set(products.map(item => item.category).filter(Boolean))] as string[]
  const columns: ColumnsType<InventoryChangeRow> = [{ title: '时间', dataIndex: 'createTime', width: 160, render: date }, { title: '门店', dataIndex: 'departmentName', width: 160 }, { title: '产品', key: 'item', width: 220, render: (_: unknown, row) => `${row.itemName} · ${row.itemCode}` }, { title: '类型', dataIndex: 'changeType', width: 100, render: (value: InventoryChangeType) => <Tag color={value === 'IN' ? 'green' : value === 'OUT' ? 'orange' : 'blue'}>{value === 'IN' ? '入库' : value === 'OUT' ? '出库' : '盘点'}</Tag> }, { title: '数量', dataIndex: 'quantity', width: 100 }, { title: '单位成本', dataIndex: 'unitCost', width: 110, render: money }, { title: '单据号', dataIndex: 'referenceNo', width: 140, render: value => value || '—' }, { title: '备注', dataIndex: 'reason', width: 180, render: value => value || '—' }]
  return <><div className="inventory-sub-actions"><Space wrap><Button type="primary" icon={<SwapOutlined />} onClick={() => onOpenChange('IN')}>产品入库</Button><Button icon={<DownloadOutlined />} onClick={() => void message.info('当前筛选结果可导出为报表')}>报表下载</Button></Space></div><div className="inventory-filter-row"><Select allowClear placeholder="全部门店" value={departmentId} onChange={value => { setDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear placeholder="请选择品牌" value={brand} onChange={value => { setBrand(value); setPage(1) }} options={brands.map(value => ({ value, label: value }))} /><Select allowClear placeholder="请选择分类" value={category} onChange={value => { setCategory(value); setPage(1) }} options={categories.map(value => ({ value, label: value }))} /><Select allowClear showSearch optionFilterProp="label" placeholder="选择产品" value={itemId} onChange={value => { setItemId(value); setPage(1) }} options={productOptions(products)} /><Select mode="multiple" allowClear placeholder="请选择入库类型" value={types} onChange={value => { setTypes(value as InventoryChangeType[]); setPage(1) }} options={[{ value: 'IN', label: '入库' }, { value: 'OUT', label: '出库' }, { value: 'ADJUST', label: '盘点' }]} /><DatePicker.RangePicker value={range} onChange={value => { if (value?.[0] && value?.[1]) setRange([value[0], value[1]]); else setRange(undefined); setPage(1) }} /><Input.Search aria-label="产品名称 / 编号 / 单据号" placeholder="产品名称 / 编号 / 单据号" allowClear onSearch={value => { setKeyword(value.trim()); setPage(1) }} /><Button icon={<ReloadOutlined />} onClick={() => setRevision(value => value + 1)} /></div><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryChangeRow> rowKey="id" loading={query.loading} columns={columns} dataSource={query.data?.records ?? []} scroll={{ x: 1120 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无相关数据' }} /><div className="catalog-footer"><span>共 {query.data?.total ?? 0} 条</span><Pagination {...paginationOptions} current={page} pageSize={10} total={query.data?.total ?? 0} onChange={setPage} /></div></>
}

function BatchWorkspace({ tenantId, platform, departments, products, revision, setRevision, writable }: { tenantId?: number; platform: boolean; departments: Department[]; products: CatalogItem[]; revision: number; setRevision: (value: (current: number) => number) => void; writable: boolean }) {
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [departmentId, setDepartmentId] = useState<number>(); const [itemId, setItemId] = useState<number>(); const [open, setOpen] = useState(false); const { modal, message } = App.useApp()
  const query = useCatalogQuery<PageResult<InventoryBatchRow>>(`/inventory/batches?page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${departmentId ? `&departmentId=${departmentId}` : ''}${itemId ? `&itemId=${itemId}` : ''}`, tenantId, revision, platform ? tenantId !== undefined : true)
  const columns: ColumnsType<InventoryBatchRow> = [{ title: '批次名称', dataIndex: 'batchName', width: 220, render: (value, row) => <div className="catalog-cell-stack"><strong>{value}</strong><span>{row.itemName} · {row.itemCode}</span></div> }, { title: '所属门店', dataIndex: 'departmentName', width: 180 }, { title: '生产日期', dataIndex: 'productionDate', width: 120, render: value => value || '—' }, { title: '到期时间', dataIndex: 'expiryDate', width: 120, render: value => value || '—' }, { title: '创建时间', dataIndex: 'createTime', width: 160, render: date }, { title: '更新时间', dataIndex: 'updateTime', width: 160, render: date }, { title: '备注', dataIndex: 'remark', width: 200, render: value => value || '—' }, { title: '操作', key: 'actions', width: 90, render: (_: unknown, row) => <Button type="link" danger disabled={!writable} onClick={() => modal.confirm({ title: `删除“${row.batchName}”？`, okText: '删除', okButtonProps: { danger: true }, cancelText: '取消', onOk: async () => { try { await catalogRequest(`/inventory/batches/${row.id}`, tenantId, { method: 'DELETE' }); setRevision(value => value + 1); void message.success('批次已删除') } catch (cause) { void message.error(errorMessage(cause)); throw cause } } })}>删除</Button> }]
  return <><div className="inventory-sub-actions"><Space wrap><Button type="primary" icon={<PlusOutlined />} disabled={!writable} onClick={() => setOpen(true)}>新建批次</Button><Button icon={<ReloadOutlined />} onClick={() => setRevision(value => value + 1)}>刷新</Button></Space></div><div className="inventory-filter-row"><Input.Search aria-label="批次名称" placeholder="批次名称" allowClear onSearch={value => { setKeyword(value.trim()); setPage(1) }} /><Select allowClear placeholder="全部门店" value={departmentId} onChange={value => { setDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear showSearch optionFilterProp="label" placeholder="选择产品" value={itemId} onChange={value => { setItemId(value); setPage(1) }} options={productOptions(products)} /></div><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryBatchRow> rowKey="id" loading={query.loading} columns={columns} dataSource={query.data?.records ?? []} scroll={{ x: 1250 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无相关数据' }} /><div className="catalog-footer"><span>共 {query.data?.total ?? 0} 条</span><Pagination {...paginationOptions} current={page} pageSize={10} total={query.data?.total ?? 0} onChange={setPage} /></div><InventoryBatchForm open={open} tenantId={tenantId} departments={departments} products={products} onClose={() => setOpen(false)} onSaved={() => setRevision(value => value + 1)} /></>
}

function InventoryBatchForm({ open, tenantId, departments, products, onClose, onSaved }: { open: boolean; tenantId?: number; departments: Department[]; products: CatalogItem[]; onClose: () => void; onSaved: () => void }) {
  const [form] = Form.useForm(); const [saving, setSaving] = useState(false); const { message } = App.useApp()
  const submit = async (values: Record<string, unknown>) => { setSaving(true); try { await catalogRequest('/inventory/batches', tenantId, { method: 'POST', body: JSON.stringify({ ...values, productionDate: values.productionDate ? (values.productionDate as Dayjs).format('YYYY-MM-DD') : undefined, expiryDate: values.expiryDate ? (values.expiryDate as Dayjs).format('YYYY-MM-DD') : undefined }) }); void message.success('批次已创建'); onSaved(); onClose(); form.resetFields() } catch (cause) { void message.error(errorMessage(cause)) } finally { setSaving(false) } }
  return <Modal className="catalog-modal" width={560} centered title="新建批次" open={open} onCancel={onClose} destroyOnClose footer={null}><Form form={form} layout="vertical" onFinish={submit} initialValues={{ status: 1 }}><Form.Item name="departmentId" label="门店 / 部门" rules={[{ required: true, message: '请选择门店' }]}><Select options={departmentOptions(departments)} /></Form.Item><Form.Item name="itemId" label="产品" rules={[{ required: true, message: '请选择产品' }]}><Select showSearch optionFilterProp="label" options={productOptions(products)} /></Form.Item><Form.Item name="batchName" label="批次名称" rules={[{ required: true, message: '请输入批次名称' }]}><Input maxLength={120} /></Form.Item><Space className="catalog-form-row" align="start"><Form.Item name="productionDate" label="生产日期"><DatePicker style={{ width: '100%' }} /></Form.Item><Form.Item name="expiryDate" label="到期时间"><DatePicker style={{ width: '100%' }} /></Form.Item></Space><Form.Item name="remark" label="备注"><Input.TextArea rows={3} maxLength={300} /></Form.Item><div className="catalog-dialog-actions"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={saving}>保存</Button></div></Form></Modal>
}

function DocumentTable({ query, page, setPage }: { query: { data?: PageResult<InventoryDocumentRow>; error: string; loading: boolean; reload: () => void }; page: number; setPage: (page: number) => void }) {
  const columns: ColumnsType<InventoryDocumentRow> = [{ title: '单据号', dataIndex: 'documentNo', width: 180 }, { title: '调出仓', dataIndex: 'sourceDepartmentName', width: 160, render: value => value || '—' }, { title: '调入仓', dataIndex: 'targetDepartmentName', width: 160, render: value => value || '—' }, { title: '日期', dataIndex: 'documentDate', width: 120 }, { title: '经办人', dataIndex: 'operatorName', width: 120, render: value => value || '—' }, { title: '状态', dataIndex: 'status', width: 100, render: (value: InventoryDocumentStatus) => <Tag color={value === 'CONFIRMED' ? 'success' : value === 'CANCELLED' ? 'default' : 'processing'}>{value === 'DRAFT' ? '草稿' : value === 'PENDING' ? '待处理' : value === 'CONFIRMED' ? '已确认' : '已取消'}</Tag> }, { title: '备注', dataIndex: 'remark', width: 200, render: value => value || '—' }]
  return <><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryDocumentRow> rowKey="id" loading={query.loading} columns={columns} dataSource={query.data?.records ?? []} scroll={{ x: 980 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无相关数据' }} /><div className="catalog-footer"><span>共 {query.data?.total ?? 0} 条</span><Pagination {...paginationOptions} current={page} pageSize={10} total={query.data?.total ?? 0} onChange={setPage} /></div></>
}

function LiquidationWorkspace({ tenantId, platform, departments, revision, setRevision, writable }: { tenantId?: number; platform: boolean; departments: Department[]; revision: number; setRevision: (value: (current: number) => number) => void; writable: boolean }) {
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [departmentId, setDepartmentId] = useState<number>(); const [range, setRange] = useState<[Dayjs, Dayjs]>(); const [open, setOpen] = useState(false); const [importOpen, setImportOpen] = useState(false)
  const query = useCatalogQuery<PageResult<InventoryDocumentRow>>(`/inventory/documents?docType=LIQUIDATION&page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${departmentId ? `&sourceDepartmentId=${departmentId}` : ''}${range ? `&startDate=${range[0].format('YYYY-MM-DD')}&endDate=${range[1].format('YYYY-MM-DD')}` : ''}`, tenantId, revision, platform ? tenantId !== undefined : true)
  return <><div className="inventory-sub-actions"><Space wrap><Button icon={<FileAddOutlined />} disabled={!writable} onClick={() => setImportOpen(true)}>导入库存盘点单</Button><Button type="primary" icon={<PlusOutlined />} disabled={!writable} onClick={() => setOpen(true)}>新建库存盘点单</Button><Button icon={<ReloadOutlined />} onClick={() => setRevision(value => value + 1)}>刷新</Button></Space></div><div className="inventory-filter-row"><Select allowClear placeholder="全部门店" value={departmentId} onChange={value => { setDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><DatePicker.RangePicker value={range} onChange={value => { if (value?.[0] && value?.[1]) setRange([value[0], value[1]]); else setRange(undefined); setPage(1) }} /><Input placeholder="单据号" allowClear onChange={event => setKeyword(event.target.value)} onPressEnter={event => { setKeyword(event.currentTarget.value.trim()); setPage(1) }} /></div><DocumentTable query={query} page={page} setPage={setPage} /><InventoryDocumentForm open={open} tenantId={tenantId} departments={departments} initialType="LIQUIDATION" onClose={() => setOpen(false)} onSaved={() => setRevision(value => value + 1)} /><InventoryCsvImport open={importOpen} tenantId={tenantId} onClose={() => setImportOpen(false)} onSaved={() => setRevision(value => value + 1)} /></>
}

function CallWorkspace({ tenantId, platform, departments, revision, setRevision, writable }: { tenantId?: number; platform: boolean; departments: Department[]; revision: number; setRevision: (value: (current: number) => number) => void; writable: boolean }) {
  const { message } = App.useApp(); const [direction, setDirection] = useState<'IN' | 'OUT'>('IN'); const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState<InventoryDocumentStatus>(); const [range, setRange] = useState<[Dayjs, Dayjs]>(); const [open, setOpen] = useState(false); const [sourceDepartmentId, setSourceDepartmentId] = useState<number>(); const [targetDepartmentId, setTargetDepartmentId] = useState<number>()
  const docType: InventoryDocumentType = direction === 'IN' ? 'TRANSFER_IN' : 'TRANSFER_OUT'
  const query = useCatalogQuery<PageResult<InventoryDocumentRow>>(`/inventory/documents?docType=${docType}&page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${status ? `&status=${status}` : ''}${sourceDepartmentId ? `&sourceDepartmentId=${sourceDepartmentId}` : ''}${targetDepartmentId ? `&targetDepartmentId=${targetDepartmentId}` : ''}${range ? `&startDate=${range[0].format('YYYY-MM-DD')}&endDate=${range[1].format('YYYY-MM-DD')}` : ''}`, tenantId, revision, platform ? tenantId !== undefined : true)
  return <><Tabs activeKey={direction} items={[{ key: 'IN', label: '调拨入库管理' }, { key: 'OUT', label: '调拨出库管理' }]} onChange={next => { setDirection(next as 'IN' | 'OUT'); setPage(1) }} /><div className="inventory-sub-actions"><Space wrap><Button type="primary" icon={<PlusOutlined />} disabled={!writable} onClick={() => setOpen(true)}>{direction === 'IN' ? '新建调拨入库' : '新建调拨出库'}</Button><Button icon={<DownloadOutlined />} onClick={() => void message.info('当前筛选结果可导出为报表')}>报表下载</Button></Space></div><div className="inventory-filter-row"><Select allowClear placeholder="调入仓库" value={targetDepartmentId} onChange={value => { setTargetDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear placeholder="调出仓库" value={sourceDepartmentId} onChange={value => { setSourceDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear placeholder="请选择调拨状态" value={status} onChange={value => { setStatus(value); setPage(1) }} options={[{ value: 'DRAFT', label: '草稿' }, { value: 'PENDING', label: '待处理' }, { value: 'CONFIRMED', label: '已确认' }, { value: 'CANCELLED', label: '已取消' }]} /><DatePicker.RangePicker value={range} onChange={value => { if (value?.[0] && value?.[1]) setRange([value[0], value[1]]); else setRange(undefined); setPage(1) }} /><Input.Search aria-label="单据号" placeholder="请输入单据号" allowClear onSearch={value => { setKeyword(value.trim()); setPage(1) }} /></div><DocumentTable query={query} page={page} setPage={setPage} /><InventoryDocumentForm open={open} tenantId={tenantId} departments={departments} initialType={docType} onClose={() => setOpen(false)} onSaved={() => setRevision(value => value + 1)} /></>
}

function AccountWorkspace({ tenantId, platform, departments, revision, setRevision }: { tenantId?: number; platform: boolean; departments: Department[]; revision: number; setRevision: (value: (current: number) => number) => void }) {
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [brand, setBrand] = useState<string>(); const [category, setCategory] = useState<string>(); const [departmentId, setDepartmentId] = useState<number>(); const [range, setRange] = useState<[Dayjs, Dayjs]>(); const query = useCatalogQuery<PageResult<InventoryAccountRow>>(`/inventory/account?page=${page}&pageSize=10&keyword=${encodeURIComponent(keyword)}${brand ? `&brand=${encodeURIComponent(brand)}` : ''}${category ? `&category=${encodeURIComponent(category)}` : ''}${departmentId ? `&departmentId=${departmentId}` : ''}${range ? `&startDate=${range[0].format('YYYY-MM-DD')}&endDate=${range[1].format('YYYY-MM-DD')}` : ''}`, tenantId, revision, platform ? tenantId !== undefined : true)
  const columns: ColumnsType<InventoryAccountRow> = [{ title: '产品品类', dataIndex: 'category', width: 150, render: value => value || '—' }, { title: '产品信息', key: 'item', width: 230, render: (_: unknown, row) => <div className="catalog-cell-stack"><strong>{row.itemName}</strong><span>{row.itemCode}</span></div> }, { title: '单位', dataIndex: 'unit', width: 80, render: value => value || '—' }, { title: '期初库存', dataIndex: 'openingQuantity', width: 110 }, { title: '入库数量', dataIndex: 'inboundQuantity', width: 110 }, { title: '出库数量', dataIndex: 'outboundQuantity', width: 110 }, { title: '期末库存', dataIndex: 'endingQuantity', width: 110 }, { title: '成本价', dataIndex: 'costPrice', width: 110, render: money }]
  function download() { const rows = query.data?.records ?? []; const csv = ['产品品类,产品信息,单位,期初库存,入库数量,出库数量,期末库存,成本价', ...rows.map(row => [row.category ?? '', row.itemName, row.unit ?? '', row.openingQuantity, row.inboundQuantity, row.outboundQuantity, row.endingQuantity, row.costPrice].join(','))].join('\n'); const url = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = '成本核算.csv'; link.click(); URL.revokeObjectURL(url) }
  const brands = [...new Set((query.data?.records ?? []).map(item => item.brand).filter(Boolean))] as string[]; const categories = [...new Set((query.data?.records ?? []).map(item => item.category).filter(Boolean))] as string[]
  return <><div className="inventory-sub-actions"><Space wrap><Button type="primary" onClick={() => setRevision(value => value + 1)}>查询</Button><Button icon={<DownloadOutlined />} onClick={download}>报表下载</Button></Space></div><div className="inventory-filter-row"><Select allowClear placeholder="全部仓库" value={departmentId} onChange={value => { setDepartmentId(value); setPage(1) }} options={departmentOptions(departments)} /><Select allowClear placeholder="全部品牌" value={brand} onChange={value => { setBrand(value); setPage(1) }} options={brands.map(value => ({ value, label: value }))} /><DatePicker.RangePicker value={range} onChange={value => { if (value?.[0] && value?.[1]) setRange([value[0], value[1]]); else setRange(undefined); setPage(1) }} /><Select allowClear placeholder="请选择产品类别" value={category} onChange={value => { setCategory(value); setPage(1) }} options={categories.map(value => ({ value, label: value }))} /><Input.Search aria-label="搜索产品" placeholder="请输入产品名称/编号" allowClear onSearch={value => { setKeyword(value.trim()); setPage(1) }} /></div><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryAccountRow> rowKey="id" loading={query.loading} columns={columns} dataSource={query.data?.records ?? []} scroll={{ x: 980 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无相关数据' }} /><div className="catalog-footer"><span>共 {query.data?.total ?? 0} 条</span><Pagination {...paginationOptions} current={page} pageSize={10} total={query.data?.total ?? 0} onChange={setPage} /></div></>
}

function InventoryWarningForm({ open, row, tenantId, onClose, onSaved }: { open: boolean; row?: InventoryRow; tenantId?: number; onClose: () => void; onSaved: () => void }) {
  const [form] = Form.useForm(); const [saving, setSaving] = useState(false); const { message } = App.useApp()
  const submit = async (values: Record<string, unknown>) => { if (!row) return; setSaving(true); try { await catalogRequest(`/inventory/${row.id}/warning`, tenantId, { method: 'PUT', body: JSON.stringify({ warningValue: values.warningValue }) }); void message.success('库存下限已更新'); onSaved(); onClose() } catch (cause) { void message.error(errorMessage(cause)) } finally { setSaving(false) } }
  return <Modal className="catalog-modal" width={480} centered title="修改库存下限" open={open} onCancel={onClose} destroyOnClose footer={null} afterOpenChange={visible => { if (visible && row) form.setFieldsValue({ warningValue: row.warningValue }) }}><Form form={form} layout="vertical" initialValues={{ warningValue: row?.warningValue ?? 0 }} onFinish={submit}><p className="catalog-form-hint">{row?.itemName ?? '库存品项'} · {row?.departmentName ?? '门店'}</p><Form.Item name="warningValue" label="库存下限" rules={[{ required: true, message: '请输入库存下限' }]}><InputNumber min={0} precision={3} style={{ width: '100%' }} /></Form.Item><div className="catalog-dialog-actions"><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit" loading={saving}>保存</Button></div></Form></Modal>
}

function InventorySettingsWorkspace({ tenantId, platform, revision, setRevision, onEditWarning }: { tenantId?: number; platform: boolean; revision: number; setRevision: (value: (current: number) => number) => void; onEditWarning: (row: InventoryRow) => void }) {
  const query = useCatalogQuery<PageResult<InventoryRow>>('/inventory?page=1&pageSize=100&keyword=', tenantId, revision, platform ? tenantId !== undefined : true)
  const columns: ColumnsType<InventoryRow> = [{ title: '产品信息', key: 'item', width: 260, render: (_: unknown, row) => <div className="catalog-cell-stack"><strong>{row.itemName}</strong><span>{row.itemCode}</span></div> }, { title: '所属门店', dataIndex: 'departmentName', width: 180 }, { title: '产品品牌', dataIndex: 'brand', width: 120, render: value => value || '—' }, { title: '产品品类', dataIndex: 'category', width: 120, render: value => value || '—' }, { title: '库存下限', dataIndex: 'warningValue', width: 120 }, { title: '当前库存', dataIndex: 'quantity', width: 120 }, { title: '操作', key: 'actions', width: 140, render: (_: unknown, row) => <Button type="link" onClick={() => onEditWarning(row)}>修改库存下限</Button> }]
  return <><div className="inventory-sub-actions"><Button icon={<ReloadOutlined />} onClick={() => setRevision(value => value + 1)}>刷新</Button></div><QueryError error={query.error} onRetry={query.reload} /><Table<InventoryRow> rowKey="id" loading={query.loading} columns={columns} dataSource={query.data?.records ?? []} scroll={{ x: 1050 }} pagination={false} locale={{ emptyText: query.loading ? <Spin /> : '暂无库存设置' }} /></>
}

export default function InventoryWorkspace({ tenantId, platform }: { tenantId?: number; platform: boolean }) {
  const { can } = useAuth(); const [params, setParams] = useSearchParams(); const rawView = params.get('view'); const view = (inventoryTabs.some(item => item.key === rawView) ? rawView : 'stock') as InventoryView; const [revision, setRevision] = useState(0); const [changeOpen, setChangeOpen] = useState<InventoryChangeType>(); const [warningRow, setWarningRow] = useState<InventoryRow>(); const enabled = platform ? tenantId !== undefined : true; const items = useCatalogQuery<PageResult<CatalogItem>>('/items?kind=PRODUCT&page=1&pageSize=100&status=1', tenantId, revision, enabled); const departments = useCatalogQuery<Department[]>('/iam/departments', tenantId, revision, enabled); const writable = platform || can('inventory:write')
  if (!platform && !can('inventory:read')) return <Result status="403" title="暂无库存管理权限" />
  const products = items.data?.records ?? []; const stores = departments.data ?? []
  function selectView(next: string) { setParams(currentParams => { currentParams.set('view', next); return currentParams }); }
  function openChange(type: InventoryChangeType) { setChangeOpen(type) }
  return <section className="catalog-panel inventory-catalog-panel"><div className="catalog-tabs-row"><Tabs activeKey={view} items={inventoryTabs.map(item => ({ key: item.key, label: item.label }))} onChange={selectView} /><Space className="catalog-actions"><Button icon={<ReloadOutlined />} aria-label="刷新库存" onClick={() => setRevision(value => value + 1)} /></Space></div><QueryError error={items.error || departments.error} onRetry={() => { items.reload(); departments.reload() }} />{view === 'stock' && <StockWorkspace tenantId={tenantId} platform={platform} departments={stores} products={products} revision={revision} setRevision={setRevision} onOpenChange={openChange} onEditWarning={setWarningRow} />}{view === 'changes' && <ChangeWorkspace tenantId={tenantId} platform={platform} departments={stores} products={products} revision={revision} setRevision={setRevision} onOpenChange={openChange} />}{view === 'batch' && <BatchWorkspace tenantId={tenantId} platform={platform} departments={stores} products={products} revision={revision} setRevision={setRevision} writable={writable} />}{view === 'liquidation' && <LiquidationWorkspace tenantId={tenantId} platform={platform} departments={stores} revision={revision} setRevision={setRevision} writable={writable} />}{view === 'call' && <CallWorkspace tenantId={tenantId} platform={platform} departments={stores} revision={revision} setRevision={setRevision} writable={writable} />}{view === 'account' && <AccountWorkspace tenantId={tenantId} platform={platform} departments={stores} revision={revision} setRevision={setRevision} />}{view === 'settings' && <InventorySettingsWorkspace tenantId={tenantId} platform={platform} revision={revision} setRevision={setRevision} onEditWarning={setWarningRow} />}<InventoryChangeForm open={changeOpen !== undefined} tenantId={tenantId} departments={stores} products={products} initialType={changeOpen ?? 'IN'} onClose={() => setChangeOpen(undefined)} onSaved={() => setRevision(value => value + 1)} /><InventoryWarningForm open={warningRow !== undefined} row={warningRow} tenantId={tenantId} onClose={() => setWarningRow(undefined)} onSaved={() => setRevision(value => value + 1)} /></section>
}
